### ISSUE TITLE
bbI2CZip: size of the output buffer

### ISSUE THREAD

**Issue by tnogueira** [joan2937/pigpio#100]
Given the check on the outLen:

https://github.com/joan2937/pigpio/blob/master/pigpio.c#L10351

the outBuf must be at least 1 byte larger than the number of bytes we actually want to read. This makes it a bit counterintuitive/unexpected for someone using the function.

Should it maybe read **_if ((bytes + outPos) <= outLen)_**   ?

The same applies to PI_I2C_WRITE.

**Comment by joan2937** [comment]
You are right. I will change lines 10351 and 10376 as you suggest for the next version (V59).

I have no timescale for that release at the moment.

**Comment by tnogueira** [comment]
Thanks for the quick reply to both issues, and keep up the great work with pigpio!

Thanks again

**Comment by joan2937** [comment]
Should be fixed in the now released V59.

**Comment by joan2937** [comment]
Assumed fixed.
