### ISSUE TITLE
What is the timeout value in gpioSetISRFunc()?

### ISSUE THREAD

**Issue by bobbywong** [joan2937/pigpio#108]
For the API:  int gpioSetISRFunc(unsigned user_gpio, unsigned edge, int timeout, gpioISRFunc_t f), what is the function ofthe timeout?

```C
//pin ButtonCenter is wired High with a resister network
//pin ButtonCenter when pressed is connected to ground

void displayInterrupt(int gpio, int level, uint32_t tick){
  printf("Interrupt %d\n", c);
  c++;
}

void main(){
...
  gpioInitialise();
  gpioSetMode(ButtonCenter, PI_INPUT); 
  gpioSetPullUpDown(ButtonCenter, PI_PUD_UP); 
  gpioSetISRFunc(ButtonCenter, FALLING_EDGE, 1, displayInterrupt);

  while(1){
  }
}
```
When I do the above, displayInterrupt() is called without the button being pressed.  

When I changed to  gpioSetISRFunc(ButtonCenter, FALLING_EDGE, 0, displayInterrupt), then displayInterrupt() is called when the button is pressed.  

Reading this "The level will be PI_TIMEOUT if the optional interrupt timeout expires." seems to tell me that the timeout value is used as a wait time before reading the pin and recording the level for the call back function.  

If this is the case, setting it to 1 should not change the behavior when it is 0.

**Comment by joan2937** [comment]
The timeout is used to get a response if the interrupt doesn't happen.  Say it is set to 1000 (milliseconds).  If the button isn't pressed for a second you would be called with a level of PI_TIMEOUT.  If the button was pressed or released within a second you would be called with a level of 0 or 1.  If there are regular (less than a second) button presses you would never be called with the timeout value.  The timeout is reset each time a level change or a timeout happens.
