### ISSUE TITLE
Sample time vs CPU utilisation

### ISSUE THREAD

**Issue by Thuffir** [joan2937/pigpio#11]
The documentation states the following figures:
```
The approximate CPU percentage used for each sample rate is:

sample  cpu
 rate    %

  1     25
  2     16
  4     11
  5     10
  8     15
 10     14
```

How were these numbers measured?
On my B+ board the sample rate of 10 us causes definitely a few percentages less utilization than 5 us.

**Comment by joan2937** [comment]
Frankly I don't remember.  They are guide figures.  I think I was running https://www.youtube.com/watch?v=2vq0Q4dD6KE at the time to get some idea myself.
