### ISSUE TITLE
gpioStartThread  detached and changelog question

### ISSUE THREAD

**Issue by MungoBerry** [joan2937/pigpio#118]
Hi,

There's a reason why thread created with gpioStartThread  is not detached ?
In your example you create 3 endless threads and stop it with gpioStopThread (that will detach it),
but what if new thread is not endless ?
The pthread_create man reports: "...when a detached thread terminates, its resources are automatically released back to the system"
It is true to not detached one ?

Exists on pigpio site and\or github a changelog for pigpio ?

Thanks.

**Comment by joan2937** [comment]
gpioStartThread and gpioStopThread are just convenience wrappers around the underlying pthreads implementation.

I really haven't given them much thought.

I'd suggest that anyone needing any special behaviour should write their own wrappers.

If you think the current implementation is demonstrably wrong could you raise an issue and include the fault and some software to demonstrate the fault.

I do not maintain a changelog for pigpio.  Sometimes I feel I should.
