### ISSUE TITLE
MCP23017 I2C for C

### ISSUE THREAD

**Issue by bichpham** [joan2937/pigpio#139]
I would like to read inputs from MCP23017 using pigpio library. Does any one have example written in C for me to look at. I have read the MCP23017 spec and I2C spec but not sure what function to use in the pigpio library.

**Comment by joan2937** [comment]
I think if anyone had a suitable example they would have responded by now.  I have given Python snippets in various forums, not sure about C.  However any C example you find should be easily portable to pigpio.  The function naming is fairly standard amongst I2C/SMBus implementations.
