### ISSUE TITLE
Wave output on the Pi 3: more info

### ISSUE THREAD

**Issue by matherp** [joan2937/pigpio#140]
My Pi 3 has always had wave output slow by a factor of 1.128 (running March version of Jessie - fully upgraded, headless) whereas a colleague running Jessie Lite on his Pi 3 was seeing perfect timing running exactly the same code.

He sent me a copy of his image and when installed on my Pi 3 I also got perfect timing so the issue is definitely OS software related.

Next try was to install the new release of Raspbian Jessie 4.9 released 21/6/17

1. With monitor, keyboard and mouse connected I was then seeing wave output slow by a factor of 1.16

2. Operating headless with no monitor, keyboard or mouse I'm now getting perfect timing.

3. Next try was to reconnect the keyboard and mouse. This resulted in the wave slow by a factor of 1.134.

4. Finally with just the monitor connected the wave goes back to being slow by 1.16

These results are completely reproducible.

My conclusion FWIW is that DMA activity associated with USB and HDMI is delaying the wave output DMA in some pretty systematic way on the Pi 3 which doesn't occur on other types of Pi

Whether this helps or not ?........

NB: all OS are absolutely default other than enabling SSH

**Comment by joan2937** [comment]
Thanks for that information.  Have you told the Raspberry Pi kernel guys?  I am convinced they have broken the clocks, mind you I expect they have a different opinion.
