### ISSUE TITLE
HWVER on a pi 2 returns a strange number

### ISSUE THREAD

**Issue by MaitreDede** [joan2937/pigpio#143]
Hi,

On a raspberry pi 2 :
```
pi@raspberrypi:~ $ pigs pigpv
60
pi@raspberrypi:~ $ pigs hwver
10489921
pi@raspberrypi:~ $ cat /proc/cpuinfo
...
Hardware        : BCM2835
Revision        : a01041
```

Is HWVER a reliable command to detect the type of board (Pi 1, 2, 3, Compute Module) ?

**Comment by electrokean** [comment]
You mean the "10489921"?  That is just the decimal equvalent of the hex "a01041"
See the list of board revisions (in hex format) here: http://elinux.org/RPi_HardwareHistory

**Comment by MaitreDede** [comment]
Ok, I was reading the doc http://abyz.co.uk/rpi/pigpio/pigs.html#HWVER .
Thanks for your help
