### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stefanpoeter** [joan2937/pigpio#145]
Under what license is this module released?

**Comment by joan2937** [comment]
It is Public Domain.  That means you can do anything you want and use any licence you choose (as can anyone else).

**Comment by stefanpoeter** [comment]
Thanks a lot.

**Comment by SlySven** [comment]
Actually - if you look on the front page (on the "code" tab) many GitHub projects report their licence - and @joan2937 's standard "Unlicence" for this library is such a project:

![screenshot_20170801_201940](https://user-images.githubusercontent.com/6163092/28842803-f4ed4b76-76f6-11e7-802a-184462349994.png)
