### ISSUE TITLE
Clean up dead handles on broken connection

### ISSUE THREAD

**Issue by Joey-1970** [joan2937/pigpio#157]
Hello,

I use PIGPIO with the socket interface. If I restart the application, I must at first reset all configurations (for example I2C-handle, notification handle, etc.).
I can do it by send "sudo killall pigpiod" and "sudo pigpiod" to reset all values, but maybe there is a "better" way?

Joachim

**Comment by guymcswain** [comment]
Change title from 'Reset all configurations with one function?' to 'Clean up dead handles on broken connection'.

Tagging this with RETEST since connections were cleaned up starting with V68.
