### ISSUE TITLE
Makefile root priviledges

### ISSUE THREAD

**Issue by tomashora** [joan2937/pigpio#17]
Would it be possible to remove sudo calls from Makefile and let people execute the script as sudo? This would solve issue eg. in Minibian where the sudo is not present.

**Comment by joan2937** [comment]
Frankly I don't remember why I did it the way I did.

I have no objection in principle to removing sudo from the script (Arch doesn't have sudo by default either).

Unless I discover a reason not to I will make the change the next time I make a release.  I'm not sure when that will be.

**Comment by joan2937** [comment]
Changed in V37.
