### ISSUE TITLE
Starting pigpiod without sudo?

### ISSUE THREAD

**Issue by Nic2012** [joan2937/pigpio#171]
Hi,
trying a special router distro for the RaspberryPi 3 from LEDE the latest 17.01.3,
https://lede-project.org/docs/instructionset/arm_cortex-a53_neon-vfpv4

Compiled like
` CFLAGS=-mfloat-abi=hard make` and installed.

Trying to run gives me:
```
root@lede:~/pigpio# /lib/ld-musl-armhf.so.1 ./pigpiod
root@lede:~/pigpio# 2017-10-15 08:00:27 initCheckPermitted:
+---------------------------------------------------------+
|Sorry, you don't have permission to run this program.    |
|Try running as root, e.g. precede the command with sudo. |
+---------------------------------------------------------+

Can't initialise pigpio library
```
Traditionally a router os has no sudo on board, but there was an add. package "sudo" that I have installed but it makes no difference. Is there any chance to startup the daemon?

```
root@lede:~/pigpio# uname -a
Linux lede 4.4.89 #0 SMP Sat Sep 30 18:37:33 2017 armv7l GNU/Linux
root@lede:~/pigpio# cat /etc/os-release
NAME="LEDE"
VERSION="17.01.3, Reboot"
ID="lede"
ID_LIKE="lede openwrt"
PRETTY_NAME="LEDE Reboot 17.01.3"
VERSION_ID="17.01.3"
HOME_URL="http://lede-project.org/"
BUG_URL="http://bugs.lede-project.org/"
SUPPORT_URL="http://forum.lede-project.org/"
BUILD_ID="r3533-d0bf257c46"
LEDE_BOARD="brcm2708/bcm2710"
LEDE_ARCH="arm_cortex-a53_neon-vfpv4"
LEDE_TAINTS="no-all"
LEDE_DEVICE_MANUFACTURER="LEDE"
LEDE_DEVICE_MANUFACTURER_URL="http://lede-project.org/"
LEDE_DEVICE_PRODUCT="Generic"
LEDE_DEVICE_REVISION="v0"
LEDE_RELEASE="LEDE Reboot 17.01.3 r3533-d0bf257c46"
```

Any idea would be appreciated.
Best regards,
Nic

**Comment by MaitreDede** [comment]
Hi @Nic2012 ,
Pigpio uses direct memory access that needs the root privileges. 
First, you can check if direct memory access is available : is `/dev/mem` present ?
Then the user that runs the application needs to have access to `/dev/mem`.

**Comment by joan2937** [comment]
Answered by @MaitreDede
