### ISSUE TITLE
GPIO serial write

### ISSUE THREAD

**Issue by gorogm** [joan2937/pigpio#176]
Dear Joan / devs,
I respect the work you put in this great library!
Let me ask about gpio (bitbang) serial writing functionality: is it supported by the library? I couldn't find it in the documentation / header, although writing functionality appears in bitbang i2c, spi.
Thanks

**Comment by joan2937** [comment]
For C see http://abyz.me.uk/rpi/pigpio/cif.html#gpioSerialReadOpen etc,  There should be similar calls for Python, pigs, etc.

**Comment by joan2937** [comment]
I closed this by mistake.

**Comment by gorogm** [comment]
Thanks Joan for the quick answer, but I would like to WRITE, however all these gpioSerial* function show only READING functionality. Even the opener is 'gpioSerialReadOpen', and I couldn't find a writer counterpart. Do I miss something? Thanks!

**Comment by joan2937** [comment]
gpioWaveAddSerial

**Comment by gorogm** [comment]
Ahhh great, thank you!

**Comment by joan2937** [comment]
My mistake.  I had forgotten that the write was different to the read (for reasons which are apparent when you write the code, I perhaps should link between the calls in the documentation).

**Comment by gorogm** [comment]
That would be helpful for future users! Anyhow, thanks for the quick help!!!
