### ISSUE TITLE
Wrong SPI speed using Raspberry Pi 3

### ISSUE THREAD

**Issue by jmmac1973** [joan2937/pigpio#180]
Hi,
I'm using the PIGPIO library for SPI communications and everything worked well in Raspberry Pi 1 (RPi as master at 10MHz). But then I switched to Raspberry Pi 3 and the SPI speed changed from 10MHz to 16MHz.

I believe the issue comes from the different VideoCore bus speeds, 250MHz in RPi1 and RPi2 and 400MHz in RPi3 (16/10 = 400/250). Maybe PIGPIO doesn't take that into consideration when calculating the clock divider ?

Jaime

**Comment by joan2937** [comment]
I believe this is the same root issue as that first mentioned in #80 and #140.

I haven't been looking very closely at posts and do not remember seeing any solution.

**Comment by jmmac1973** [comment]
The following page is relevant to the issue and offers a solution (that worked for me).

https://github.com/raspberrypi/linux/issues/2094

Solution: add 'core_freq=250' into /boot/config.txt/

**Comment by guymcswain** [comment]
If your setup is headless (no monitor) and you have no audio configurations please report back that status.  Otherwise I'm tagging this as an hdmi/audio interaction issue with available work-around.

**Comment by jmmac1973** [comment]
I'm no longer working on that project but my setup was headless. I didn't used audio but can't confirm my audio configurations. Probably I removed everything not essential to the project.
