### ISSUE TITLE
undefined reference to makedev

### ISSUE THREAD

**Issue by github-k8n** [joan2937/pigpio#188]
Build on raspberry pi zero w with gentoo fails with the error above.
This is probably due to glibc-2.24+ not including sysmacros.h from types.h

Thus, please #include <sys/sysmacros.h>
in pigpio.c

Adding this line fixes the issue.

**Comment by github-k8n** [comment]
Hi, that would be great if that could be added.
I'm also creating an ebuild for gentoo (currently using HEAD on the git repo),
are there any plans to have release versions or will this just stay fluid?

**Comment by joan2937** [comment]
Should be fixed in V65.
