### ISSUE TITLE
Pigs exit code

### ISSUE THREAD

**Issue by machadotiago** [joan2937/pigpio#198]
When running pigs, even when it fails, the return code is always 0.
For example:
```
pi@pi:~ $ pigs r 20; echo $?
socket connect failed
0
```
Shouldn't it return an error code != 0 if a problem occurs?

**Comment by joan2937** [comment]
I have not given that any thought before.  I will think about it.

**Comment by joan2937** [comment]
I will add the following status codes in V67 (defined in the new file pigs.h).

```
PIGS_OK            0
PIGS_CONNECT_ERR 255
PIGS_OPTION_ERR  254
PIGS_SCRIPT_ERR  253
```
If more than one condition applies the highest numbered error code will be reported.
