### ISSUE TITLE
Use .so versioning

### ISSUE THREAD

**Issue by github-k8n** [joan2937/pigpio#207]
Hi,

in order to ensure future compatibility for any major backwards-incompatible changes to the library I would recommend to add versioning information. (i.e. use version "0" for the current library) by installing the libraries with .so.0 and creating symbolic links pointing to them instead of directly installing them as .so (see also https://en.wikipedia.org/wiki/Soname ):

The changes to the Makefile would be to name the libraries with .0 at the end and adding the links:

```
+	ln -srf $(DESTDIR)$(libdir)/libpigpio.so.0 $(DESTDIR)$(libdir)/libpigpio.so
+	ln -srf $(DESTDIR)$(libdir)/libpigpiod_if.so.0 $(DESTDIR)$(libdir)/libpigpiod_if.so
+	ln -srf $(DESTDIR)$(libdir)/libpigpiod_if2.so.0 $(DESTDIR)$(libdir)/libpigpiod_if2.so
```

Thanks,
Daniel

**Comment by joan2937** [comment]
I think this has now been done.
