### ISSUE TITLE
Cross compile failing

### ISSUE THREAD

**Issue by horfee** [joan2937/pigpio#211]
Hello,

I am trying to compile it in my buildroot env.
it seems that the install/uninstall instructions related to python setup and ldconfig are not meant to work with crosscompiling setup.

Could you correct that please ?

**Comment by joan2937** [comment]
How?

**Comment by horfee** [comment]
basically,

replace : ldconfig by $(LDCONFIG)
and define 
LDCONFIG?=ldconfig

then you should not trigger the python setup, as not all system are hosting python, so I would suggest to add a target to install the python part
Next, you should submit your excellent library to the buildroot team, to have it included in standard in the configuration menus.
I can share with you my buildroot def for this library if you want

**Comment by horfee** [comment]
Here is mine : 
After downloading the package, the build will fail : you will have to comment the line related to python stuff.

#
# basic building rules
#
PIGPIO_VERSION = 934874be2fa34a525beb33e8cb75e378df587860
PIGPIO_SITE = git://github.com/joan2937/pigpio
PIGPIO_SITE_METHOD = git

PIGPIO_INSTALL_STAGING = YES
PIGPIO_INSTALL_TARGET = YES

define PIGPIO_BUILD_CMDS
    $(MAKE) CC="$(TARGET_CC)" INSTALL="$(INSTALL)" AR="$(TARGET_CROSS)ar" RANLIB="$(TARGET_CROSS)ranlib" SIZE="$(TARGET_CROSS)size" STRIP="$(TARGET_CROSS)strip" LD="$(TARGET_LD)" -C $(@D) all
endef

define PIGPIO_INSTALL_STAGING_CMDS
    $(MAKE) CC="$(TARGET_CC)" INSTALL="$(INSTALL)" AR="$(TARGET_CROSS)ar" RANLIB="$(TARGET_CROSS)ranlib" SIZE="$(TARGET_CROSS)size" STRIP="$(TARGET_CROSS)strip" LD="$(TARGET_LD)" LDCONFIG="$(TARGET_CROSS)ldconfig" DESTDIR=$(STAGING_DIR) -C $(@D) install
endef

define PIGPIO_INSTALL_TARGET_CMDS
    $(MAKE) CC="$(TARGET_CC)" INSTALL="$(INSTALL)" AR="$(TARGET_CROSS)ar" RANLIB="$(TARGET_CROSS)ranlib" SIZE="$(TARGET_CROSS)size" STRIP="$(TARGET_CROSS)strip" LD="$(TARGET_LD)" LDCONFIG="$(TARGET_CROSS)ldconfig" DESTDIR=$(TARGET_DIR) -C $(@D) install
endef

#$(eval $(autotools-package))
#$(eval $(call GENTARGETS,package,pigpio))
$(eval $(generic-package))




And here the Config.in :
config BR2_PACKAGE_PIGPIO
	bool "pigpio"
	help
		PIGPIO pigpio is a library for the Raspberry which allows control of the General Purpose Input Outputs (GPIO).  pigpio works on all versions of the PI.
		see http://abyz.co.uk/rpi/pigpio/index.html


You will have to configure the Config.in, and maybe the systemd config.in to enable activating the deamon pigpiod

**Comment by Sjoerd82** [comment]
I had to change the `@d` to `@D` to make it run (turns out it's Github trying to markup the post). But then it crashed on ldconfig. According to Buildroot IRC, ldconfig should not run in the makefile, commenting that out, and fixing the Python error (disclaimer, not tested Python3 or uninstall):

```
diff --git a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -92,13 +92,13 @@
        install -m 0755 pig2vcd           $(DESTDIR)$(bindir)
        install -m 0755 pigpiod           $(DESTDIR)$(bindir)
        install -m 0755 pigs              $(DESTDIR)$(bindir)
-       if which python2; then python2 setup.py install; fi
-       if which python3; then python3 setup.py install; fi
+       if which python2; then python2 setup.py install --prefix=$(TARGET_DIR)/usr; fi
+       if which python3; then python3 setup.py install --prefix=$(TARGET_DIR)/usr; fi
        install -m 0755 -d                $(DESTDIR)$(mandir)/man1
        install -m 0644 *.1               $(DESTDIR)$(mandir)/man1
        install -m 0755 -d                $(DESTDIR)$(mandir)/man3
        install -m 0644 *.3               $(DESTDIR)$(mandir)/man3
-       ldconfig
+       #ldconfig

 uninstall:
        rm -f $(DESTDIR)$(includedir)/pigpio.h
@@ -110,11 +110,11 @@
        rm -f $(DESTDIR)$(bindir)/pig2vcd
        rm -f $(DESTDIR)$(bindir)/pigpiod
        rm -f $(DESTDIR)$(bindir)/pigs
-       if which python2; then python2 setup.py install --record /tmp/pigpio >/dev/null; xargs rm -f < /tmp/pigpio >/dev/null; fi
-       if which python3; then python3 setup.py install --record /tmp/pigpio >/dev/null; xargs rm -f < /tmp/pigpio >/dev/null; fi
+       if which python2; then python2 setup.py install --prefix=$(TARGET_DIR)/usr --record /tmp/pigpio >/dev/null; xargs rm -f < /tmp/pigpio >/dev/null; fi
+       if which python3; then python3 setup.py install --prefix=$(TARGET_DIR)/usr --record /tmp/pigpio >/dev/null; xargs rm -f < /tmp/pigpio >/dev/null; fi
        rm -f $(DESTDIR)$(mandir)/man1/pig*.1
        rm -f $(DESTDIR)$(mandir)/man3/pig*.3
-       ldconfig
+       #ldconfig

 $(LIB1):       $(OBJ1)
        $(SHLIB) -o $(LIB1) $(OBJ1)
```
Installation finishes successfully. But running the daemon gives me a library error (related to not running ldconfig perhaps?). I've not had the time yet to dig deeper. But I take it you didn't encounter this problem?
```
# pwd
/usr/local/bin
# ./pigpiod
/usr/local/bin/pigpiod: can't load library 'libpigpio.so'
```

**Comment by rossburton** [comment]
Using the CMake file may be better than the raw Makefile, but that does hardcode install paths.  Using GNUInstallDirs would be helpful.

**Comment by guymcswain** [comment]
I believe this issue was resolved but the issue never closed.  The current Makefile has changed relative to how the python setup and ldconfig are handled.
