### ISSUE TITLE
Arbitrary frequencies using clock dividers for PWM

### ISSUE THREAD

**Issue by MaPePeR** [joan2937/pigpio#214]
From looking at the source and documentation it appears the library does not allow to use arbitrary frequencies for (hardware) pwm by using the `source/(div_i + div_f/4096)` clock divider.

**Comment by joan2937** [comment]
That is correct, it doesn't.

**Comment by MaPePeR** [comment]
Then this isn't a question, but a feature request.

**Comment by joan2937** [comment]
It may sound like a trivial request but I suspect it isn't.  It would need an additional API with knock on changes to pigs, the Python module, the pigpio C I/F, and pigpiod_if2 I/F, as well as related documentation.

I'm not saying it would not be a useful addition.  I am saying I'm not prepared to put in all the effort required.
