### ISSUE TITLE
pigpiod daemon make reboot or shutdown very long Raspberry 3 B+

### ISSUE THREAD

**Issue by xamix** [joan2937/pigpio#216]
Hello everyone,

I'm on the last Raspberry 3B+ and last Raspbian Desktop.
_pigpiod_ is working for me on Python 3.

However when the dameon **pigpiod** is launched, then the _reboot_ or _shutdown_ or even _poweroff_ take about 3 minutes instead of few seconds without **pigpiod** daemon. 

I'm connected with SSH and type **sudo poweroff** or **sudo reboot** and then it seem starting powering off, screen is black and in bottom left border it print **plymouth-reboot.service** for about 3 mintutes...

Do you have any idea about the problem?

Regards

**Comment by guymcswain** [comment]
I run _pigpiod_ on zero-w, 1B, 1B+, 2, 3 connected via SSH and don't have this problem.  I'm using Raspbian Lite exclusively.

**Comment by xamix** [comment]
Since it was only for control hardware PWM, I changed my program by using overlay and **sysfs**.
So I not use pigpiod anymore.
