### ISSUE TITLE
Makefile python2 vs python3

### ISSUE THREAD

**Issue by tomashora** [joan2937/pigpio#22]
The makefile is hardcoded to install for both python version 2 and 3 making the installation fail when any of the version is not present.

It would be nice to see detection of python version and installing only if present.

http://stackoverflow.com/questions/4933285/how-to-detemine-python-version-in-makefile

**Comment by joan2937** [comment]
I have no particular problem with this, I'll just amend the Makefile along the following lines.

Instead of

>python2 setup.py install

I'll use

>if which python2; then python2 setup.py install; fi

**Comment by tomashora** [comment]
Much easier solution... Thanks!

**Comment by joan2937** [comment]
Added to V38.
