### ISSUE TITLE
Calling `exit` from a signal handler isn't safe

### ISSUE THREAD

**Issue by jonas-schievink** [joan2937/pigpio#220]
Here's a snippet from inside `sigHandler`, which calls `exit` at two occasions:

https://github.com/joan2937/pigpio/blob/934874be2fa34a525beb33e8cb75e378df587860/pigpio.c#L5518-L5532

According to `man 7 signal`, this is not a safe thing to do. Only `_Exit` and `_exit` are async-signal-safe, not the regular `exit`. In my case, this causes my `atexit` handler to run in signal context, which is very unexpected.

(note that this might not be the only signal safety issue in the handler)

**Comment by joan2937** [comment]
If exit is called in that function something pretty dreadful has already happened.  Continuing as if nothing is wrong may not be sensible, aborting is probably the right solution.

What would you do?  Other threads are already potentially compromised.

**Comment by jonas-schievink** [comment]
The code is executed when the program is killed via `SIGINT` or `SIGTERM`, nothing is compromised in that case. You also shouldn't exit with a code of -1 in that case, which indicates an error.

I think it's best to just shutdown pigpio normally and *don't* call any exit function. The default action of the signal will then be executed and usually terminate the process.

**Comment by guymcswain** [comment]
@jonas-schievink , Do you have a proposal for a change?  If so, we will evaluate it.

**Comment by jonas-schievink** [comment]
Call _exit or _Exit instead of exit. I'm not qualified to review the handler for other signal safety issues though.

**Comment by guymcswain** [comment]
The signal handling was implemented in support of the daemon (pigpiod).  You can turn off the signal handler if you don't want to use it:
```c++
gpioCfgSetInternals(PI_CFG_NOSIGHANDLER);
```

**Comment by jonas-schievink** [comment]
The signal handler invokes undefined behavior. Please reopen until that is fixed.

**Comment by guymcswain** [comment]
Are you using the pigpiod?

**Comment by jonas-schievink** [comment]
I don't remember. It's still undefined behavior, whether it's in the daemon or not.

**Comment by guymcswain** [comment]
Yes, but as Joan stated, if things are in the midst of crashing, does it matter?  I suppose I could make the change.  Have you tested it?

**Comment by jonas-schievink** [comment]
> if things are in the midst of crashing, does it matter?

Unfortunately yes, or I wouldn't have opened this issue – having `atexit` handlers called from a signal handler is very unexpected behavior. In my case I think it was some ROS handler running and causing havoc.

> Have you tested it?

No, as I no longer have access to the hardware.

**Comment by guymcswain** [comment]
Will you help me to write a test case?  I'd like some confirmation that whatever change is made to the source if having the intended behavior (and that nothing else breaks).

**Comment by jonas-schievink** [comment]
I can try, but I'm not a C programmer. Basically you need to:

* Register an `atexit` handler
* Setup pigpio
* Send a SIGINT signal to yourself using `raise(SIGINT);`
  * This will now call the registered handler, but should not (technically it's UB, so the handler doesn't *have* to be called)

**Comment by guymcswain** [comment]
Can you please clarify?

> , but should not (technically it's UB, so the handler doesn't have to be called)

**Comment by jonas-schievink** [comment]
Yeah, `atexit` handlers are only called by `exit`, not the async-signal-safe alternatives `_exit` and `_Exit`.

**Comment by joan2937** [comment]
I would not make any change to the existing behaviour.  Undefined behaviour is just that, an unknown number of people will be depending on the current behaviour.
