### ISSUE TITLE
Setting pulselength for 433 RF transmitter

### ISSUE THREAD

**Issue by Pezura** [joan2937/pigpio#221]
I have been previously using RCSwitch with my Raspberry PI to send 433 RF codes to local devices(lights and outlets) in my house. This is mimicking 433 RF remote controls that come with these devices. Unfortunately it sometimes sends more than one transmission and I'm not really a fan of this.

I used your python example to send the 433 command and I can see that it's sending it successfully. The only issue is that I can't seem to figure out how to set the pulse length. I also recorded the code from the remote with piscope. I found some code you posted to playback a piscope file but when I play that back it doesn't use the right pulse length from the remote.

Without the pulse length being the same as the remote the device doesn't get the signal. I'd prefer to use pigpio but I'm stuck on this, do you have any suggestions?

**Comment by joan2937** [comment]
The comments in the code example should be enough to work out the pulse length and how to change it.
