### ISSUE TITLE
pigpiod fails due to permissions in Docker container running resin/raspberrypi3-node

### ISSUE THREAD

**Issue by mdbeauche** [joan2937/pigpio#235]
I'm having issues getting pigpiod to run in a default Docker container running default resinOS resin/raspberrypi3-node.

Dockerfile:

```
FROM resin/raspberrypi3-node

RUN apt-get update && apt-get install -yq --no-install-recommends pigpio

RUN npm install pigpio
```

From running docker (`docker run -it name /bin/bash` and then `sudo pigpiod` at shell as root):

```
2018-09-06 19:55:38 initCheckPermitted: 
+---------------------------------------------------------+
|Sorry, you don't have permission to run this program.    |
|Try running as root, e.g. precede the command with sudo. |
+---------------------------------------------------------+


root@1bd67dc5c6e4:/# Can't initialise pigpio library
```

I've tried changing docker run permissions (`--privileged` and `--cap-add=ALL`) and I get the same result. Made a post on the resin.io forums [here](https://forums.resin.io/t/pigpio-failing-on-lack-of-permissions-using-resin-raspberrypi3-node/3917), not sure where the issue is originating.

**Comment by jw3** [comment]
Try `--privileged -v /sys:/sys -v /dev/mem:/dev/mem`

**Comment by mdbeauche** [comment]
Similar error:

```
root@6461e1d79455:/# pigpiod
root@6461e1d79455:/# 2018-09-10 16:45:44 initPeripherals: mmap gpio failed (Operation not permitted)
Can't initialise pigpio library
```

**Comment by jw3** [comment]
I have been using the resin jre image recently with pigpio, not sure what the problem is but it can be done.

Here are some references to that recent work
- https://github.com/jw3/docker-pigpio
- https://hub.docker.com/r/jwiii/pigpio/
- https://github.com/jw3/pigpio-scala-examples

**Comment by jw3** [comment]
Did you try to specify root user from command line `-u root`?

**Comment by mdbeauche** [comment]
Yes, I've tried specifying root from both the command line and the Dockerfile (you see I'm logged in as root in the prompt).

I've been running pigpiod (the daemon) just as a faster way to get to this error rather than running my own code.

**Comment by hegelstad** [comment]
Did you solve this @mdbeauche ?

**Comment by cmisztur** [comment]
Here is a working dockerfile

https://github.com/corbosman/node-red-gpiod/blob/master/Dockerfile

**Comment by guymcswain** [comment]
> RUN npm install pigpio

If you are running the Node.js binding of pigpio (yep confusing) then you don't need the daemon - pigpiod.  The nodejs pigpio library initializes pigpio (the C lib).  But maybe I missed something in this thread.
