### ISSUE TITLE
How to best use Threads??

### ISSUE THREAD

**Issue by jdalicandro** [joan2937/pigpio#237]
First - thank you for all you've done - - it's been quite straightforward to bring my Raspberry pi v3 B+ up and connect simultaneously to the multitude of sensors.

Here's my question:
 - I've connected my RPI to multiple sensors:
 - - - (1) ultrasonic sensor (HC-SR04) - directly connected to 2 GPIOs (as Trigger and Echo)
 - - - (2) IR distance sensors (Sharp GP2y0a02yk0F) connected through ADCs (mcp3002)
 - also I've connected my RPI to a Naza M v2 flight controller

Additionally, I'd like to have my RPI respond to commands sent through SSH.

Problem is cannot simply wait on getchar(), as this blocks everything else.

Originally, I was going to create a thread to wait on the getchar(); but this doesn't seem to align with how you created threads (on the GPIOs).

So, now I'm thinking that the operation of the sensors can be made into threads.

Which would be the best way to simultaneously operate sensors while "waiting on an SSH command" ?

Thank you for answering my question...

**Comment by guymcswain** [comment]
It sounds like you are controlling sensors through pigpio using a C program and then you want the ability to remotely access the sensors as well.  If that assumption is correct, you can achieve this by using the socket interface and the pigpiod daemon.  Write you C program using the pigpiod C I/F.  Now you can access the same sensors remotely from your choice of C program or higher level script languages Python or Javascript.
