### ISSUE TITLE
port basic functionalities for OPi Zero

### ISSUE THREAD

**Issue by deeagle001** [joan2937/pigpio#242]
Hello,

Thank you for the great work. I am using your project for my hobby projects.
Awesome.

But recently I changed my main platform to OPi Zero, as it has all the functionality I need, cost and consumes less.

Even though it is similar to the RPi, I found no reliable GPIO framework.
I tried ArmbianIO (C, Python), OPi.GPIO but all of them failed to reliable call a callback function upon a 10 us of pulse. (Exactly the same code works on RPI). Few of them was missed out of a few hundred.

BTW. I was wondering that is it possible to port the basic functionalities to OPi Zero. GPIO read/write, and edge event callbacks.
I checked that the H2+ chip has DMA, and I am willing to help in that, just do not know where to start.

I took a short look at your implementation and I could not find layers for platform abstraction, which I can implement for other platforms.

What do you think? Is it possible, and can I make it with help?

**Comment by guymcswain** [comment]
Sorry but no architectures other than Raspberry Pi will be supported by pigpio.
