### ISSUE TITLE
Question--Getting timestamp of last GPIO change.  Is a callback required?

### ISSUE THREAD

**Issue by davthomaspilot** [joan2937/pigpio#246]
I have an application with some (relatively) critical timing requirements.  Events need to occur at a time relative to a message being received on the UART (goal of +/- 1 msec accuracy).

I have high level code (Qt C++) that creates a signal whenever a file descriptor becomes readable.  That signal can be used to trigger code execution.

However, I think the latency from when the character is ready to read in the UART to when my C++ code executes could be large relative to 1 millisecond.  But, that's ok if I had an accurate time stamp for when the  last GPIO on the RXD pin occured.

I see that I can register a callback function to be called whenever a GPIO changes.  Parameters passed to the callback function include include a structure with a "tick" parameter.

I really don't need the callbacks at every transition of the RxD pin (aka GPIO15).  It would be better to make a pigpio call when the uart becomes readable to get the timestamp of the last transition.

Is it possible to make a call to get the same data that's passed to a callback function (which includes the tick for when the GPIO transitioned)?

**Comment by davthomaspilot** [comment]
Also, I'm assuming that functions like  ::gpioSetAlertFunc will work on GPIO 15, even it's configured to be the output of the UART?

Thanks!

**Comment by guymcswain** [comment]
Yes, you can register callbacks on GPIO15 while configured as the UART's output.

**Comment by davthomaspilot** [comment]
> Yes, you can register callbacks on GPIO15 while configured as the UART's output.

Maybe that's true... But...

ttyAMA0 is on pins 14 (TxD) & 15 (RxD).  I can configure the UART and read/write until I do this:


`::gpioSetISRFunc(15, EITHER_EDGE,0,PigSpi::rxdChanged);`

After doing this, I get the callbacks, but the file descriptor never again becomes readable.

Is this expected, or should it be an issue?

(I used gpioSetISRFunc instead of ::gpioSetAlertFunc, since the latency was much lower.  And, I couldn't find a way to configure how often the code that calls ::gpioSetAlertFunction could be configured to poll more often than one milliscecond.)

I was going to use the ISR to assign a time stamp to each received character from the UART.  I guess I'll try doing the bit bang version of serialRead, and maybe hacking the code in pigpio to get a time stamp for each char.

In addition to time-stamping each character, I need to make a hardware spi transfer during a specific 750 usecond period, that can only be identified by 250 usec of ones on RxD (running at 48 usec per bit, 203800 baud).

I know I may have to punt and go to a dedicated processor, but I'm exploring the feasibility of doing it on the Pi using pigpio.

Comments welcome!

**Comment by guymcswain** [comment]
I have not used the ISRfunc API so can't comment on the issue.

Sounds like you want more than a timestamp.  Are you trying to respond to an external event within a critical window of time?

**Comment by davthomaspilot** [comment]
Yes, I'm trying to respond to an external event within a critical.  The event is period of 750 usec period of 1's on the uart input.  When that occurs, I need to send an SPI command within 125 usec.

I was thinking I could use a watchdog timer that would call a function to do the SPI when it expires.  That would be in a different thread than the one doing the per char timestamping.

Feasible?

**Comment by guymcswain** [comment]
While the pigpio library provides many timing capabilities that are OS independent, it cannot do what you are asking.  Any thread that it spawns will be subject to the preemptive nature of the operating system.

I stand to be corrected, but I think you need a real-time OS or bare metal programming.  (Arduino?)

**Comment by joan2937** [comment]
Guy is quite correct.  pigpio can accurately time incoming GPIO level changes and accurately schedule outgoing GPIO level changes.  However it can not guarantee a response time, that is down to the underlying Linux system.

gpioSetISRFunc uses Linux's interrupt handling code.  You need to try with gpioSetAltertFunc if you don't want to screw up the serial handling.

**Comment by davthomaspilot** [comment]
Thanks for the reply...

I have a processor on the board, if I can't get it done on Linux.  That's my fallback.  But, it will complicate the overall system considerably.

But, I was thinking I could elevate the thread priority so that it rarely gets preempted.  It's not a disaster if it does occasionally take to long to initiate the SPI.  That will be recognized and the code can try again.

On the ::gpioSetISRFunc issue, you can see that pin 15 is labelled INPUT instead of ALT in gpio readall (wiringPi) after the call is made.

If this is not know behaviour, I'll try the same thing with  gpioSetAlertFunc

**Comment by davthomaspilot** [comment]
Joan, your reply didn't show up until after I posted my last reply.

What is the thread priority of the ISR?  Can it be pre-empted?

Also--

>  and accurately schedule outgoing GPIO level changes

That's great!  So, even if my process gets pre-empted, an output GPIO will toggle when scheduled?  I guess I haven't read enough to figure out how that's done.  

I'm not doing anything like PWM.  I need to schedule an event several seconds in the future, but with something like 1 msec accuracy relative to an input transition.  The SPI xfer relative to a series of 1's on the UART (software or hardware) is done only once, and can utilize retries.

**Comment by davthomaspilot** [comment]
> and accurately schedule outgoing GPIO level changes

I guess you mean using gpioWaveAdd?  

If the transition is guaranteed to occur at the scheduled time (wrt Linux pre-empting the process), then that opens up some other possibilities.

Thanks!

**Comment by davthomaspilot** [comment]
Sorry for yet another question.  Is there a good place to ask pigpio questions?

The latency for gpioSetISRFunc is quite low compared to gpioSetAltertFunc.  But, as noted, gpioSetISRFunc on the RxD pin "kills" hardware UART receive.

Can I use a spare gpio that's hardware connected to the RxD pin (15) and use gpioSetISRFunc without impacting use of the hardware UART?  Or, does  "use Linux's interrupt handling code" mean the hardware UART can't be used for receive, regardless of which pin the gpioSetISRFunc is associated with?

**Comment by davthomaspilot** [comment]
I tried using a spare GPIO that's connected to the hardware RxD for the ISR gpio.  It seems to work fine!

I grab a gpioTick in the ISR code and save it along with the gpio transition timestamp.  Typical difference (which is latency to my code in ISR) is 10 - 20 usec.  (I realize it can occasionally be much longer).

This is MUCH better than what can be achieved with the alertFunc, since

>  The thread which calls the alert functions is triggered nominally 1000 times per second. 

I still  may end up using a modified version of the pigpio bit bang serial read (or even "punting" and use a dedicated processor).  But, It just seems like use of the hardware UART might keep more cpu resource free for handling the time critical stuff.  

It's fun trying to get it working on Linux using pigpio as is!  Great job Joan, and whoever else deserves credit.

**Comment by joan2937** [comment]
As you have noticed using gpioSetISRFunc will change the mode of a GPIO to be an INPUT.  That function uses the Linux interrupt handler, that's what they need to do to work.

You could link the RX line with a wire to a spare GPIO and use gpioSetISRFunc on the spare GPIO.  That will work fine.  You could also set RT priority on your process as you suggest.  See https://github.com/joan2937/pigpio/blob/bb352d2000d8a4f38bab430927a85b7af4f70a01/pigpio.c#L8150 for an example.

**Comment by davthomaspilot** [comment]
I'm going to try the SCHED_FIFO after I "benchmark" what I get at normal priority.

I noticed that even when I specify EDGE_FALLING when registering the ISR, sometimes the level is "1" when the ISR is executed.  I think this means pigpio code got interrupted between the time it assigned the timestamp versus when it sampled the level?

There  shouldn't be any bounce in the signal.  The driving signal is an adjacent pin, so ringing should be also minimal, though I do have an o-scope on the pin right now.

I really only need a timestamp per character, not for every transition.  So, maybe it's ok to miss some transitions, especially if they can be identified by level being "wrong".

Here's a sample of what I saved in the ISR.  I'm sending 5 characters of \x55.  (The \x55 gives the maximum transition rate).  Baud rate is 20833, or 48 usec per character.  Maximum transition rate is 98 usec.

TImestamp column is what was passed to the ISR.  The first line of code in the ISR does a gpioTick.  The level, timestamp tick, and "now" tick are saved in an array.  A print is done after all five characters have been received



Level | timestamp    | ISR tick          | Lat | Edge Delta

1       | 1555224706 | 1555224808 | 102 |  
1       | 1555225082 | 1555225097 | 15   | 376
0       | 1555225139 | 1555225150 | 11   | 57
0       | 1555225238 | 1555225248 | 10   | 99
0       | 1555225326 | 1555225337 | 11   | 88
0       | 1555225427 | 1555225437 | 10   | 101
0       | 1555225519 | 1555225530 | 11   | 92
0       | 1555225615 | 1555225625 | 10   | 96
0       | 1555225710 | 1555225720 | 10   | 95
0       | 1555225811 | 1555225821 | 10   | 101
1       | 1555225919 | 1555225930 | 11   | 108
0       | 1555226011 | 1555226021 | 10   | 92
0       | 1555226204 | 1555226214 | 10   | 193
0       | 1555226296 | 1555226306 | 10   | 92
0       | 1555226385 | 1555226396 | 11   | 89
0       | 1555226479 | 1555226489 | 10   | 94
0       | 1555226573 | 1555226583 | 10   | 94
0       | 1555226669 | 1555226679 | 10   | 96
1       | 1555226814 | 1555226825 | 11   | 145
0       | 1555226868 | 1555226878 | 10   | 54
0       | 1555226957 | 1555226967 | 10   | 89

**Comment by davthomaspilot** [comment]
Also, for some reason, the first ISR call always seem to have much longer latency and is much more likely to have a 1 level.

**Comment by davthomaspilot** [comment]
I abandoned trying to use the hardware UART for getting timestamps on received characters.  Instead, I did what Joan had suggested--use a modified version of gpioSerial read.

I did that, and it's working really well for what I need.  

But, the hacks I did to pigpio.c may is probably not the smartest way to do it.  My priority was to first make sure it works.   I welcome suggestions on a way to do it "cleaner".

Of course, the problem with doing it this way, is that I will have to diff and merge the hacks with new versions of pigpio.   So, I'd like to have a way to do it without having to touch the pigpio source.

I defined a new structure, that is identical to wfRxSerial_t but with a uint32_t* for the character timestamps.  I called the structure wfRxSerial_ts (ts for timestamp):

```
typedef struct
{
   char    *buf;
   uint32_t bufSize;
   uint32_t *tickBuf;
   int      readPos;
   int      writePos;
   uint32_t fullBit; /* nanoseconds */
   uint32_t halfBit; /* nanoseconds */
   int      timeout; /* millisconds */
   uint32_t startBitTick; /* microseconds */
   uint32_t nextBitDiff; /* nanoseconds */
   int      bit;
   uint32_t data;
   int      bytes; /* 1, 2, 4 */
   int      level;
   int      dataBits; /* 1-32 */
   int      invert;
} wfRxSerial_Ts;
```


I added a wfRxSerial_ts member  to the  union in wfRx_t structure and called it ts:

```
typedef struct
{
   int      mode;
   int      gpio;
   uint32_t baud;
   pthread_mutex_t mutex;
   union
   {
      wfRxSerial_t s;
      wfRxSerialTs_t ts;
      wfRxI2C_t    I;
      wfRxSPI_t    S;
   };
} wfRx_t;
```

I added a new "mode" that is used in the alert function that's registered for the gpio:

`#define PI_WFRX_SERIAL_TS 10
`
The alert function now looks like this:

```
static void waveRxBit(int gpio, int level, uint32_t tick)
{
   switch (wfRx[gpio].mode)
   {
      case PI_WFRX_SERIAL:
         waveRxSerial(&wfRx[gpio], level, tick);
      case PI_WFRX_SERIAL_TS:
         waveRxSerialTs(&wfRx[gpio], level, tick);
   }
}
```
The timestamp version of the alert function (waveRxSerialTs) saves  the startTickBit for the timestamp:

```
...
  if (w->ts.bit > w->ts.dataBits)
      {
         memcpy(w->ts.buf     + w->ts.writePos, &w->ts.data, w->ts.bytes);
         memcpy(w->ts.tickBuf + w->ts.writePos, &w->ts.startBitTick, w->ts.bytes *sizeof(uint32$
         /* don't let writePos catch readPos */

         newWritePos = (w->ts.writePos + w->ts.bytes) % (w->ts.bufSize);
...
```
I also needed a _ts versions of gpioSerialReadOpen and gpioSerialRead.  The gpioSerialReadOpen_ts is identical to gpioSerialReadOpen except it mallocs space for  the tickBuf, and sets a different mode, so the hacked version of the alert function will get called:

```
...
 wfRx[gpio].gpio = gpio;
   wfRx[gpio].mode = PI_WFRX_SERIAL_TS;
   wfRx[gpio].baud = baud;

   wfRx[gpio].ts.buf      = malloc(SRX_BUF_SIZE);
   wfRx[gpio].ts.tickBuf = malloc(SRX_BUF_SIZE * sizeof(uint32_t));

..
```
Finally, a new function: 

`int gpioSerialReadTs(unsigned gpio, void *buf, void *startTicksBuf, size_t bufSize)`

Has an extra parameter for a pointer to a uint32_t buffer to hold a timestamp for each character.  The startTicksBuf is copied to the buffer with the addition of one line:


>      if (buf) memcpy(buf, w->ts.buf+w->ts.readPos, bytes);
>       _if (startTicksBuf) memcpy(startTicksBuf, w->ts.tickBuf+w->ts.readPos,bytes*sizeof(uint32_t));_
>       w->ts.readPos += bytes;

**Comment by guymcswain** [comment]
Closing this issue as the original question(s) were answered.  The remainder of this thread discusses a custom function which I don't believe has broad applicability to the community.  Thank you for sharing and good luck.
