### ISSUE TITLE
Attribute error in I2C Slave sample program

### ISSUE THREAD

**Issue by Scott216** [joan2937/pigpio#249]
I'm using the example program "I2C slave device".  I have an RPi 2 Model B connected to an Arduino (one of the 3.3 volt versions, not 5v).  RPi GPIO 19 (pin 35) is connected to SCL pin on Arduino and GPIO 18 (pin 12) is connected to SDA on the Arduino.  I also have GND connected together on both.  When I run the python program, I get this error:

e = pi.event_callback(pigpio.EVENT_BSC, i2c)
AttributeError: pi instance has no attribute 'event_callback'

**Comment by joan2937** [comment]
I assume you are using an old version of pigpio.
