### ISSUE TITLE
Is data transmission safe with Gpiozreo?

### ISSUE THREAD

**Issue by Tinymaxi** [joan2937/pigpio#253]
The thing is at school we have to transfer data from one Pi to a nother Pi. Wher

by we need to type in Numbers on a keypad at one end and it needs to control a 7-segment on the other Pi connected via Ethernet cable (I have that all set up and running ;-). The data transmission needs to be secure. If for example if the code is corrupted on the way by a magnetic field for example it should recognise that and not show the wrong data. That would be ideal. Currently I am using the Gpiozero Libery to do the transmission. Wher as one Pi is the deamon. May be I could send back a signal and that would show the user if it was corrupted (Just a thought). My questionn is if it does have some feature that checks the data or makes sure the data is tranferd safe? Some Protocoll. It can never be a hundred procent but it still needs some check on it. I would be realy greatfull for your reply.

**Comment by guymcswain** [comment]
> My questionn is if it does have some feature that checks the data or makes sure the data is tranferd safe? Some Protocol

Yes.  Transport Control Protocol (TCP) is used by pigpio socket interface (if you are connecting remotely to the pigpio daemon you are using sockets).  TCP is a reliable transport with guaranteed delivery.
