### ISSUE TITLE
Writing variable values to file using a script

### ISSUE THREAD

**Issue by stegm** [joan2937/pigpio#258]
I wonder if it is possible to write data from a variable to a file using scripts. I tried the following command, but got an 'ERROR: illegal script command'.

```
pigs proc ld v0 48 fo /tmp/foo 10 sta v100 fw v100 v0 fc v100
```

It seems that the `fw`-command does not accept variables neither for the handle nor for the data.

What I tried to do in the example:
* `ld v0 48` - Save the value 48 (ASCII '0') in the variable `v0`
* `fo /tmp/foo 10` - create a new file
* `sta v100` - store the file handle in the variable `v100`
* `fw v100 v0` - write the data of `v0` using the handle `v100`
* `fc v100` - close handle `v100`

**Comment by joan2937** [comment]
I'm afraid (as you found) that will not work.

Not all commands work within scripts.

When I get time I will add a list of the commands which will not work to the pigpio documentation.
