### ISSUE TITLE
intGpioSetISRFunc with function pointer NULL should close the opened file descriptor

### ISSUE THREAD

**Issue by zanppa** [joan2937/pigpio#261]
pthISRThread opens a file descriptor (line 11375 in pigpio.c at the moment) for a gpio which will be kept open even if the thread is destroyed.

intGpioSetISRFunc with function pointer NULL calls gpioStopThread, which should close the open file descriptor in addition to deleting the thread.

As a result, if the ISR function is changed frequently, pigpio opens up new file descriptor until it crashes. This happens e.g. with some radio modules which use one pin for different functions depending on the operation mode. If the mode is changed often (rx to tx for example) and the ISR is always changed, the software will crash quite quickly.

**Comment by joan2937** [comment]
A fix will be in V69.
