### ISSUE TITLE
bsc_arduino.py doesnt work on gpio2 and gpio3

### ISSUE THREAD

**Issue by maxholgasson** [joan2937/pigpio#265]
Hi,

I can't get running the example bsc_arduino.py
Is it possible to use gpio2 and gpio3 for this i2c example?

**Comment by joan2937** [comment]
No, see http://abyz.me.uk/rpi/pigpio/python.html#bsc_xfer

The BSC peripheral uses GPIO 18 (SDA) and 19 (SCL) in I2C mode.
