### ISSUE TITLE
if condition and pigpio

### ISSUE THREAD

**Issue by maxholgasson** [joan2937/pigpio#270]
Hi,
how can I start a script when I got over I2C the message "Message123"

i dont get it why print(d[:-1]) returns the message in the example and how I can use it to compare it with a condition like if (returnedmsg == "Message123") { start script }

**Comment by joan2937** [comment]
If you want to reopen this issue you will have to give far more context.  Also make sure it is an actual issue with pigpio, not just a programming question.
