### ISSUE TITLE
Callback with bank 2 GPIOs (>31)

### ISSUE THREAD

**Issue by apica-alfred** [joan2937/pigpio#272]
There are functions to interact Bank 2 pins, but the [callback](http://abyz.me.uk/rpi/pigpio/python.html#callback) functionality only supports user_gpio (0-31). Is it possible to increase the range to support all pins?

I've found #177 that seems to be related (DMA configuration). Is the same issue?

Thank you

**Comment by joan2937** [comment]
The very earliest versions of pigpio did monitor GPIO 32-53.  The functionality was removed as a waste of resources (memory and processing time) as well as because the GPIO are not accessible to other than the compute module.

I will not be making any changes in this area.
