### ISSUE TITLE
write works but pwm doesn't on pi zerow

### ISSUE THREAD

**Issue by BryanCrotaz** [joan2937/pigpio#292]
repro, driving LED strip via MOSFET (works perfectly with servoblaster, but I want the socket interface of pigpio)
using first pigpio v.64, then upgrading to v71 (with same result)
```
sudo pigpiod
pigs mg 3
1
pigs prg 3
255
pigs p 3 127
... lights do not come on
pigs dgc 3
127
pigs w 3 1
... lights come on
pigs w 3 0
... lights go off
```

**Comment by joan2937** [comment]
Please download and run [monitor.py]http://abyz.me.uk/rpi/pigpio/examples.html#Python_monitor_py)

Does GPIO 3 toggle when you send PWM?

**Comment by BryanCrotaz** [comment]
Interesting. Yes it does. with d=625

**Comment by joan2937** [comment]
servoblaster perhaps churns out at 50 Hz?  Perhaps you want the `pigs s` command?
