### ISSUE TITLE
rawWaveAddSPI doc help

### ISSUE THREAD

**Issue by u0078867** [joan2937/pigpio#309]
Hi,

regarding the online example of MCP3008, I don't understand some parts of the following:

`rawWaveAddSPI(&rawSPI, offset, SPI_SS, buf, 2, BX, B0, B0);`

In particular:

1) `2`: what are 2 bits to transfer? 

2) from the MCP3008 datasheet, I see 3 bytes needs to be transmitted, while the buffer here keeps only 2 bytes
![Untitled](https://user-images.githubusercontent.com/1182881/70625051-e766e480-1c21-11ea-8a20-f7c1140707ed.png)

Indeed the example for [bbSPIXfer](http://abyz.me.uk/rpi/pigpio/cif.html#bbSPIXfer) moves 3 bytes.

Perhaps 1) and 2) are closely related.

Thanks!

**Comment by joan2937** [comment]
I'm afraid you are on your own with this one.  I don't have the time to get back up to speed with how these functions work to be able to offer any advice.

**Comment by guymcswain** [comment]
The pigpio documentation for this API states:

> Not intended for general use.

This API is also listed under the "expert" catagory.  Read between the lines, this means you should consult the source code directly to understand its behaviour.   As Joan states, 'you are on your own with this one'.
