### ISSUE TITLE
Question:  Any quick way of re-enabling callbacks after callback.cancel()

### ISSUE THREAD

**Issue by wmarchewka** [joan2937/pigpio#326]
It appears the only way to enable a callback after it is canceled is to reissue the callback?

**Comment by joan2937** [comment]
Yes.  Why are you cancelling a callback if you want to use it still?

If you want to temporarily ignore a callback I suggest you add logic to your callback function.

```python
def my_callback(gpio, level, tick):
   if enabled:
      # handle callback
   else:
      # ignore callback
```
