### ISSUE TITLE
Use of /dev/gpiomem instead of /dev/mem

### ISSUE THREAD

**Issue by carbonarius** [joan2937/pigpio#336]
First of all, thanks for the great work. I really like to work with pigpio!

Is there a plan to switch over to using /dev/gpiomem instead of /dev/mem?
As far as I understand, /dev/gpiomem maps only the memory area needed for the gpio access and not the whole memory. 
This would make it possible to run programs linked against libpigpio to run as non-root, which I would prefer.

Regards, 
carbonarius

**Comment by joan2937** [comment]
There is no plan to do so.  pigpio uses /dev/mem for all sorts of purposes quite separate to the need to access the GPIO registers.
