### ISSUE TITLE
PIGPIO event_cancel 

### ISSUE THREAD

**Issue by eslavko** [joan2937/pigpio#355]
Hello..
In pigpio event callback is bug/wrong documentation. Even example doesn't work.
_cb1 = pi.event_callback(22, cbf)
cb1.event_cancel()_

Throw error
_AttributeError: _event instance has no attribute 'event_cancel'_

The correct syntax should be:
_ cb1.cancel()_

**Comment by guymcswain** [comment]
Please provide more information.

**Comment by eslavko** [comment]
cb1.event_cancel() throws error.
in forum I got response that cb1.cancel() is correct syntax. So manual is wrong.

**Comment by guymcswain** [comment]
I think you are referring to the documentation example under API `event_callback()` that shows the use of a non-existent method `event_cancel()`.  

This appears to be a documentation error.  Thank you.

**Comment by eslavko** [comment]
Correct!
