### ISSUE TITLE
PIGPIO under Arch

### ISSUE THREAD

**Issue by Loris1123** [joan2937/pigpio#38]
When you install pigpio under archlinux on raspi, the shared libraries won't be found.

I managed to use it by moving `libpigpio.so` `libpigpiod_if.so` and `libpigpiod_if2.so` from `/usr/local/lib` to `/usr/lib`

**Comment by joan2937** [comment]
If anyone has any robust tips for recognising the correct library locations for different distributions I will try to take them on board.

**Comment by WebReflection** [comment]
not sure why this got closed (problem still there) but I've written up an how to for ArchLinux:
https://medium.com/@WebReflection/how-to-raspi-io-on-archlinux-5d59229e5763
