### ISSUE TITLE
Script Operations

### ISSUE THREAD

**Issue by MRIIOT** [joan2937/pigpio#380]
Using Python [callback](http://abyz.me.uk/rpi/pigpio/python.html#callback) function, I am watching rising edge of pin 22.

Using default pigpiod timing the callback is invoked every 1 second.
`tag 999 w 22 1 mils 1000 w 22 0 mics 5 jp 999`

Removing the delay after pullling pin 22 low, the callback is sporadic at best.
`tag 999 w 22 1 mils 1000 w 22 0 jp 999`

Would the usage of WAIT be correct here or is a delay of a single pigpiod cycle in above working script the correct approach?
`tag 999 w 22 1 mils 1000 w 22 0 wait 0x200000 jp 999`

Thanks
Chris

**Comment by joan2937** [comment]
Why jp (jump positive).  I think you should be using an unconditional jmp (jump).

**Comment by guymcswain** [comment]
Marking this with 'no action' and will close unless an issue can be identified.
