### ISSUE TITLE
Does pigpio support the I2C GPIO expanders SX150x ?

### ISSUE THREAD

**Issue by annaertd** [joan2937/pigpio#390]
We use a RPi CM3+ module with I2C GPIO expander SX1509.
Our /boot/config.txt contains the following dtoverlay:

_dtoverlay=sx150x,sx1509-0-70,sx1509-0-70-int-gpio=8_

Does pigpio contain an API to control/configure the 16 IO pins of this expander?

**Comment by guymcswain** [comment]
No, not directly.  You would need to implement some interface code using the pigpio APIs.
