### ISSUE TITLE
gpioSetTimerFunc NULL cancel error

### ISSUE THREAD

**Issue by smdjeff** [joan2937/pigpio#397]
The gpioSetTimerFunc documentation suggests a timer can be canceled by simply passing null as the function parameter. However, this results in a soft error related to the millis parameter range. If the function parameter is null, the check for PI_MIN_MS should probably be skipped.

**Comment by guymcswain** [comment]
Without having checked the source, this sounds reasonable.  Would you care to submit a pull request?  I will merge it to the develop branch soon after and whenever the next release is made - likely toward the end of year- it'll get merged into master.

**Comment by guymcswain** [comment]
Fixed in v79
