### ISSUE TITLE
gpioSetPWMfrequency highest frequency?

### ISSUE THREAD

**Issue by smdjeff** [joan2937/pigpio#398]
The documentation states `gpioSetPWMfrequency(25, 100000); // Set GPIO25 to highest frequency.`
However, when I use high values (above 4000 in particular) it seems the output turns off completely. This is a bit confusing since the default seems to be 800 which suggests the sample rate of 5. And the table in the documentation shows it going to 8000.

`5:  8000  4000  2000 1600 1000  800  500  400  320 250   200   160  100   80   50   40   20   10
`
 Ideally, I'd like to move the PWM to about 10-20kHz so I can't hear it. Any suggestions?

**Comment by joan2937** [comment]
Where is you code?  The documentation is correct.
