### ISSUE TITLE
pigpio conflicts with audio playback

### ISSUE THREAD

**Issue by smdjeff** [joan2937/pigpio#399]
Audio playback still seems to I2C/PCM work, but seems to be playing at half speed.

**Comment by smdjeff** [comment]
A workaround for the audio playback problem seems to be calling gpioCfgClock() with the PWM setting. Why is PCM the default given it will conflict with audio?

The documentation for gpioCfgClock() isn't clear. The description seemed to suggest it was used to configure a sample rate for both the PWM and PCM peripherals. However, its main purpose is to select which of the two peripherals are to be used by the gpio library while also configuring the sample rate for that peripheral.
http://abyz.me.uk/rpi/pigpio/cif.html#gpioCfgClock

**Comment by joan2937** [comment]
Start the pigpio daemon with the -t0 option to use the PWM chip for timing.

http://abyz.me.uk/rpi/pigpio/pigpiod.html

**Comment by joan2937** [comment]
http://abyz.me.uk/rpi/pigpio/faq.html#Sound_isnt_working
