### ISSUE TITLE
Software serial emulation interfering with audio

### ISSUE THREAD

**Issue by masterX244** [joan2937/pigpio#40]
When using software serial mode sending audio is converted to random noise
Is there a mode avoiding the usage of the hardware PCM module?

**Comment by joan2937** [comment]
I'm afraid not.

pigpio is always sampling the GPIO.  The sampling is timed with either the PWM or PCM peripherals.

Waves (which implement transmitted bit bang serial data) are timed with the PWM or PCM peripheral not being used for sampling the GPIO.

In effect you lose both the PWM and PCM audio capabilities once you use pigpio waves.
