### ISSUE TITLE
Wiegand example code has decoding error.

### ISSUE THREAD

**Issue by jacoka** [joan2937/pigpio#401]
Reading error was generated by too wide bit length, your original code try to set serial code on 34 bits, but int32 (wieg->num) have 32 bits only.

I have modified your code and works perfectly.

**Comment by guymcswain** [comment]
I would be happy to accept a pull request or a patch with the specific code change(s).

**Comment by guymcswain** [comment]
> I have modified your code and works perfectly.

@jacoka , do you care to share your modification?  If not I'll be closing this issue.  Thanks in advance.
