### ISSUE TITLE
Two devices both managed by CE0 (pin8)

### ISSUE THREAD

**Issue by oosavu** [joan2937/pigpio#407]
Hello!
I'm developing raspberry-pi-zero - based PCB board with this properties:
1. I use one hardware spi ("main SPI peripheral" in trerminology of pigpio documentation).
2. i have two peripheral devices on this bus.
3. switching between this devices should be managed by setting CE0 (pin 8) to high or low. devices switched automatically on my pcb by another chip based on CE0 value.  CE1 value is not matter. so:
 ---- CE0 is low -> device 1 is active
 ---- CE0 is high -> device 2 is active

My goal is very quickly execute this loop:
while(true){
communicate with device 1;
communicate with device 2;
}

I tried to use linux SPI driver first. It works well. i open /dev/spidev0.0 and /dev/spidev0.1 and actually then i'm using /dev/spidev0.1 pin8 automatically setting to low so my custom chip select logic was success. but i have a bad performance (seems that spi kernel module makes a strange pause before each transaction).

Therefore i tried to use pigpio c library. The speed was growing up, but unfortunately i have a mistake: For device 1 it works well, but i can't open device 2 right way. I has try many combination of spiFlags bits, but it's not working, i still communicate with device 1, not device 2.

This is my c++ code:
`	
        int init = gpioInitialise();

	hDevice1 = spiOpen(0, _spiSpeed, 0);

	hDevice2 = spiOpen(1, _spiSpeed, 0b00000000); // trying to use many combination of u2 u1 u0 p2 p1 p0 bits

        while(true){

            spiXfer(hDevice1, dataFor1, dataFor1, dataFor1Size);

            spiXfer(hDevice2, dataFor2, dataFor2, dataFor2Size); // ERROR. Actually communicate with device1!!!

        }

        spiClose(hDevice1)

        spiClose(hDevice2)
`

Sorry for my bad English and thanks for help!

**Comment by guymcswain** [comment]
I think I understand what you are trying to do but I don't think SPI devices can work that way.

In your example, device 1 is working because it sees the CE pin transition for each byte that is sent.  But device 2 will never see CE transition until device 1 is selected.  

If you look at the CE pins on an oscilloscope you will observe 16 pulses, assuming the transmit FIFO is full.
