### ISSUE TITLE
[pigpiod_if2] always returning 0 in get_PWM_dutycycle does not make sense

### ISSUE THREAD

**Issue by hulloanson** [joan2937/pigpio#408]
As far as I understand, this function is supposed to get current dutycycle of a gpio pin, which the equivalent command would be `pigs gdc 18` if I wanted to get dutycycle of pin 18.

Yet as mentioned in documentation and in actual runs, it always returns 0. What is it supposed to accomplish? How do I get pwm dutycycle with the pigpiod_if2 api?

![image](https://user-images.githubusercontent.com/9977536/99934063-dc0bbb00-2d97-11eb-9361-565dc74032a8.png)

**Comment by joan2937** [comment]
Given that it works properly for me I suggest you add example code which does not work for you.

**Comment by hulloanson** [comment]
I am sorry. There was a problem with outputting the reading on my side. It now returns the correct number :)

I still suggest we modify the documentation to make it clear though.

**Comment by hulloanson** [comment]
Pull request: https://github.com/joan2937/pigpio/pull/413

**Comment by guymcswain** [comment]
Fixed in v79
