### ISSUE TITLE
Writing a Python module with pigpio

### ISSUE THREAD

**Issue by paviro** [joan2937/pigpio#41]
Hi!
I have a function which can fade some LEDs, it works without a problem. When I put the function into another file, import it into my main file and call it from there I get the following error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/pigpio.py", line 923, in run
    lastLevel = _pigpio_command(self.control,  _PI_CMD_BR1, 0, 0)
  File "/usr/local/lib/python2.7/dist-packages/pigpio.py", line 835, in _pigpio_command
    dummy, res = struct.unpack('12sI', sl.s.recv(16))
AttributeError: 'NoneType' object has no attribute 'recv'
```
Same thing when using an event like a button press from the build in GPIO Python library.

**Comment by joan2937** [comment]
There is not enough context to be sure what is happening.

Where do you connect to the daemon, e.g. pi = pigpio.pi(), and how do you pass "pi" to the called module?

**Comment by paviro** [comment]
I am using pi-blaster now which works. I called it inside the module.

**Comment by joan2937** [comment]
I'm closing this as it seems to be more of how do I write a Python program than a issue with pigpio.
