### ISSUE TITLE
Using parameters/variables in pigs scripts

### ISSUE THREAD

**Issue by sneakers-the-rat** [joan2937/pigpio#416]
Hello! I'm using the script interface via python, and I can't tell exactly what the intended way to refer to variables and parameters is. 

For example, if i wanted a script that skipped part of the script if `p0` was positive, currently i'm doing this:

`lda 0 cmp p0 jn 999 (some part of the script to skip) tag 999 (the rest of the script)`

loading 0 into the accumulator and then using `cmp` (though the sign ends up being flipped because `cmp = A-x` )

This, eg. doesn't work, but it seems like it should:

`p0 jn 999`

Not exactly a bug because that works, but i was just wondering if there was a better way of doing it. the syntax above seems natural to me, and i could try to implement if you think that's a good idea.

thanks for your work on this, really love the library.

**Comment by guymcswain** [comment]
> but i was just wondering if there was a better way of doing it. the syntax above seems natural to me, and i could try to implement if you think that's a good idea.

Unless @joan2937 is, I'm not inclined to support enhancements to the script APIs.  Aside from the nostalgia of writing assembler like code, scripts provide little that cannot be accomplished by other means.  There is also the potential downside of using multiple scripts running simultaneously or concurrently with the socket interface (ie your python module) -see issue 392.
