### ISSUE TITLE
pigpiod running on a ESP32 ??

### ISSUE THREAD

**Issue by louisvangeldrop** [joan2937/pigpio#425]
I am using the pigpiod running on a Raspberry Pi Zero W. Nice, but expensive compared to a ESP32. The pigpiod is an excellent tool and could  be used on more devices than a Raspberry Pi. I hope you like my suggestion?

**Comment by joan2937** [comment]
pigpio's most unique features are the DMA sampling and time-stamping of GPIO and the DMA generation of accurately timed GPIO level changes.  These functions are implemented on the Broadcom SoC only available in Raspberry Pis.

If you can port those features to another device you can port pigpio.

Without those features pigpio is pretty much a standard C library.

**Comment by louisvangeldrop** [comment]
I will have a look at the moddable javascript engine. It fully supports the ESP32 and if performance is an issue I always can use a C-routine.
