### ISSUE TITLE
gpioCfgClock messing up /dev/serial0 comms

### ISSUE THREAD

**Issue by NBroomfield** [joan2937/pigpio#448]
I added gpioCfgClock(5, 0, 0) to work around an issue with the library messing up the i2s peripherial which I'm using but now my comms via /dev/serial0 are messed up, any suggestions? I'm not actually using pigpio for anything complex just reading an writing to some pins, so I don't need complex PWM or interrupts on pins.

Thanks

**Comment by guymcswain** [comment]
How are you using pigpio?  If using the daemon, restart the daemon using `sudo pigpiod -t 0`.

**Comment by NBroomfield** [comment]
Thanks but I'm not using the daemon.

**Comment by guymcswain** [comment]
Then did you set `gpioCfgClock()` accordingly?

**Comment by NBroomfield** [comment]
Not sure? I read the manual... What would your recommend? Thanks :-)

**Comment by guymcswain** [comment]
> I added gpioCfgClock(5, 0, 0) to work around an issue with the library messing up the i2s peripherial ...

Sorry, you have done so already.  I don't see how this has anything to do with the serial port.

**Comment by guymcswain** [comment]
> I'm not actually using pigpio for anything complex just reading an writing to some pins, so I don't need complex PWM or interrupts on pins.

You may be interested in this library instead:
https://github.com/joan2937/lg

**Comment by NBroomfield** [comment]
Thanks I'll take a look.

**Comment by NBroomfield** [comment]
I think this was a red herring, please close.
