### ISSUE TITLE
error: 'F_SETPIPE_SZ' undeclared when compiling

### ISSUE THREAD

**Issue by nightrider77** [joan2937/pigpio#458]
Hello.

Trying to compile pigpio for arm platform with uClibc toolchain (Linux 4.9.37 armv7l).
Having error:

```
pigpio.c: In function 'gpioNotifyOpenWithSize':
pigpio.c:12029:21: error: 'F_SETPIPE_SZ' undeclared (first use in this function)
       i = fcntl(fd, F_SETPIPE_SZ, bufSize);
                     ^~~~~~~~~~~~
pigpio.c:12029:21: note: each undeclared identifier is reported only once for each function it appears in
Makefile:48: recipe for target 'pigpio.o' failed
```

Checked possible solution to add **#define _GNU_SOURCE**, but this file already has this line of code...

How to solve this?

Thanks.

**Comment by nightrider77** [comment]
Temporarily fixed it with

`i = 1024 * 64;`

**Comment by guymcswain** [comment]
Closing due to insufficient information to determine if an issue with pigpio exists.
