### ISSUE TITLE
What this fix implemented?  In version 78 or 79?  I just encountered it on Pi OS buster Debian 10 (fully patched as of today).  Happen to be running 78.

### ISSUE THREAD

**Issue by dachshund-digital** [joan2937/pigpio#466]
What this fix implemented?  In version 78 or 79?  I just encountered it on Pi OS buster Debian 10 (fully patched as of today).  Happen to be running 78.

May 03 00:12:29 pi3modelb0 pigpiod[32482]: 2021-05-03 00:12:29 initInitialise: bind to port 8888 failed (Cannot assign requested address)
May 03 00:12:29 pi3modelb0 pigpiod[32482]: Can't initialise pigpio library
M

_Originally posted by @dachshund-digital in https://github.com/joan2937/pigpio/issues/298#issuecomment-830949171_

**Comment by joan2937** [comment]
Initialisation has failed because some other process is already using port 8888.  You need to find out which process is using port 8888.

**Comment by dachshund-digital** [comment]
That is the not case, I confirmed via netstat that such was not happening, but clearly there is some type of resource conflict  This happens randomly usually when I happen to upgrade from say 78 to 79 for example.

**Comment by guymcswain** [comment]
@dachshund-digital please change the title of this issue as it is confusing - refers to a closed issue which was fixed as far back as version 74.

I see that Debian 10.9 was released end of March.  I will try to upgrade one of my platforms to see if I can reproduce.  Any additional information would be helpful.

**Comment by dachshund-digital** [comment]
Just what I showed... that sometimes the daemon stop is not clean, i.e. the port seems to be put into limbo, can't be re-acquired as expected is what it seems like.  I have seen this most often when I do a compile from source, upgrading from say 78 to 79 for example.  Before I run the new version, I typically do a systemctl stop pigpiod (which stops 78), which should release all resources, right?  Then when I do a systemctl restart pigpiod (which starts 79) I see the above issue.  Humm.... does make install stop and start any existing variant of the daemon?

**Comment by guymcswain** [comment]
I don't believe make touches anything dealing with systemd.  The package manager may have a stale `pigpiod.service` file.  Check it against the one in the repo.

**Comment by dachshund-digital** [comment]
Yeah, and we worked through a lot of issues with the unit file some time ago.  We added an improved PID kill command to make sure at system shutdown and reboot, the daemon did not hold up the sequence.  That has been working well actually thus far.   Of course a reboot, clears the issue, as well.
