### ISSUE TITLE
Sensor readout while wave_tx_busy()

### ISSUE THREAD

**Issue by philippjunger** [joan2937/pigpio#470]
Dear all,

first of all I want to thank you joan for creating this amazing PIGPIO lib!
I am using it to create a nice ramp for my stepper motor, using a TMC2208 (Trinamics) motor driver.

After some troubleshooting I managed to get the PIGPIO work as I want it to.
Now I want to read out my "homing" sensor while the stepper is moving to check if a limit was reached.

I am using the following code to read out the sensor while the chain is in progress.
The function "checkLimits will return true if a sensor is active.

```
# Check if limits are reached during movement
        while (pi.wave_tx_busy()): # While transmitting.    
            if (checkLimits(axis,steps,PUL)):
                pi.wave_tx_stop()
                break
            sleep(0.1)
```
The problem is, that my PWM is looking really bad when this while loop is active and the motor is doing noisy movement.
Even if I just enter:

```
# Check if limits are reached during movement
        while (pi.wave_tx_busy()): # While transmitting.    
		sleep(0.1)
```

It behaves the same. It feels like the while loop is disturbing the wave chain progress.
Is there any better way to read out the sensor after hitting the pi.wave_chain(chain) command?

Thank you very much, I really appreciate your help!
Philipp

**Comment by guymcswain** [comment]
When you just play the waveform, without any looping, is your stepper motor performing noise/jitter free?

Heavy network traffic on the pi will induce some additional jitter - on the order of 3-4 microseconds - on top of a baseline of 2-3 us jitter.  (These were my observations I made quite some time ago.)

**Comment by philippjunger** [comment]
When just playing the wave, the stepper motor is doing fine without any problems.

**Comment by guymcswain** [comment]
> The problem is, that my PWM is looking really bad when this while loop is active...

Is there any way you can quantify the problem and provide a script that we can use to reproduce?

**Comment by philippjunger** [comment]
Sure :) So this is the code that shows what is going on, I tried to delete everything unnecessary :)
Highly appreciate your fast help!

```
# Moves an axis by number of steps
def moveBy (axis, steps, speed):
    pi.write(setupPi.ENA, setupPi.ENA_Locked)
    
# Check if movement is allowed or position is at top or button
    if (checkLimits(axis, steps, PUL)):
        print('ERROR: No movement allowed, already at top/bottom position')

    else:
        pi.set_PWM_dutycycle(PUL, 128)  # PWM 1/2 On 1/2 Off

        # Create Ramp Wave
        #up, stay and down are just arrays with increasing and decreasing frequency
        generate_ramp(up+stay+down,PUL) 
        
        # # Check if limits are reached during movement
        while (pi.wave_tx_busy()): # While transmitting.    
            if (checkLimits(axis,steps,PUL)):
                pi.wave_tx_stop()
                break
           sleep(0.1)

    # Stop/Release motor 
    pi.set_PWM_dutycycle(PUL, 0)  # PWM off
    return

def generate_ramp(ramp, PUL):
    """Generate ramp wave forms.
    ramp:  List of [Frequency, Steps]
    """
    pi.wave_clear()     # clear existing waves
    length = len(ramp)  # number of ramp levels
    wid = [-1] * length

    # Generate a wave per ramp level
    for i in range(length):
        frequency = ramp[i][0]
        micros = int(500000 / frequency)
        wf = []
        wf.append(pigpio.pulse(1 << PUL, 0, micros))  # pulse on
        wf.append(pigpio.pulse(0, 1 << PUL, micros))  # pulse off
        pi.wave_add_generic(wf)
        wid[i] = pi.wave_create()

    # Generate a chain of waves
    chain = []
    for i in range(length):
        rampsteps = int(ramp[i][1])
        x = abs(rampsteps) & 255
        y = abs(rampsteps) >> 8
        chain += [255, 0, wid[i], 255, 1, x, y]
    
    pi.wave_chain(chain)  # Transmit chain.

# Checks if the sensor is becoming active e.g. if the limits are reached
def checkLimits(axis,steps,PUL):
    sens_nfc_input = pi.read(setupPi.sens_nfc)

    # NFC lower Limit reached?
    if (sens_nfc_input == True):
        print('WARNING: NFC lower limit with some steps left to execute')
        return 1
```

**Comment by philippjunger** [comment]
So this is a direct comparison of noice of the two movements. The first is without the "while (pi.wave_tx_busy()" part and the second is with it. The motor is also not at the correct position at the end when using the "while" loop.

https://user-images.githubusercontent.com/74316765/119476267-31785300-bd4e-11eb-89e8-880b580643b5.mov
https://user-images.githubusercontent.com/74316765/119476239-2a514500-bd4e-11eb-89ae-f225904cfae0.mov

**Comment by guymcswain** [comment]
Since I don't have a stepper motor handy, I will be looking at the output pin with an oscilloscope to see any distortion that might be the cause of the motor noise.  If you have such a scope trace it would nice to see it for comparison.

Also, why the `pi.set_PWM_dutycycle(PUL, 128)` before transmitting the wave chain?  PWM will be turned off whenever waves are transmitting.

**Comment by guymcswain** [comment]
What is the range for your ramp frequency and steps?

I'm using a simple three tuple ramp of 1900, 2000, 2100 for frequency and 60000 steps for each.  I have my scope display set to infinite persistence to see the jitter.  With the 'while loop' I see about 8 us.  Without it I see about 6 us.  I don't think I'm seeing the problem that would cause the motor noise.

**Comment by guymcswain** [comment]
Closing due to lack of response.
