### ISSUE TITLE
Debugging Wave Output Without Scope

### ISSUE THREAD

**Issue by xloem** [joan2937/pigpio#471]
I'm trying to send out a square wave using pigs and don't appear to be getting the right output.  Is there a way within pigpio to see what is happening, without having to connect an oscilloscope of some kind?

Both of these are working for me to generate a square wave, which is audible as a noise as I hear my device on a relay rapidly toggling:
```
for ((i=0; i<100; i++)); do pigs w 4 1; pigs w 4 0; done
pigs pwm 4 127
```
PWM makes an audible noise for any frequency between 10 and 1000 hertz.

Waveforms are not working for me; I do not hear the device toggling:
```
pigs wvag 4 0 25000 0 4 25000
pigs wvcap 50
pigs wvtxr 0
```

Additionally, this is not working for me; I do not see any output while the above commands are running:
```
pigs no
pigs nb 0 0xffff
pigs2vcd /dev/pigpio0
```

I have built pigs and pigpiod from git master.

**Comment by joan2937** [comment]
WVAG use bit positions to identify the GPIO.

For a visual use piscope.

http://abyz.me.uk/rpi/pigpio/piscope.html

For a listing look at monitor.py

http://abyz.me.uk/rpi/pigpio/examples.html#Python_monitor_py

When using waves make sure you set any GPIO you use to outputs.

N.B. waves use bits to identify the GPIO (remember multiple GPIO may be set/cleared in each wave triplet).

pigs m 4 w

pigs wvag 16 0 25000 0 16 25000

Generally for GPIO x.

G=((1<<x))

pigs wvag $G 0 25000 0 $G 25000

**Comment by xloem** [comment]
Thanks so much, it was totally using bits in the wave generation.

**Comment by xloem** [comment]
@joan2937 so you know, monitor.py also does not work on output pins.  it seems it is best to do some wiring if debugging on output pins is needed.

**Comment by joan2937** [comment]
@xloem monitor.py works on all GPIO regardless of their mode.  Why do you think it does not work on output GPIO?

**Comment by xloem** [comment]
I received no output for pins set to output, when I drove them, same as the behavior of the notification events above.

**Comment by joan2937** [comment]
@xloem If you have time can you give an example showing the problem.  I'll try it on my Pi.
