### ISSUE TITLE
Aperiodicity/distortion of sipmle periodical signal

### ISSUE THREAD

**Issue by tanshihaj** [joan2937/pigpio#477]
I've noticed that on my Raspberry PI Zero W signal generated with commands

```
pi@raspberrypi:~ $ sudo pigpiod
pi@raspberrypi:~ $ G=23; pigs m $G w; BG=$((1<<G)); pigs wvag $BG 0 10 0 $BG 10; pigs wvcre; pigs wvtxr 0
```

Looks like that on oscilloscope:
<img width="1419" alt="Screen Shot 2021-07-04 at 21 42 15" src="https://user-images.githubusercontent.com/5421525/124396256-1582ac80-dd11-11eb-8411-af4c73c8fdb2.png">

or like that (distortion changes from time and sometimes disappear):
<img width="1416" alt="Screen Shot 2021-07-04 at 21 47 28" src="https://user-images.githubusercontent.com/5421525/124396316-714d3580-dd11-11eb-9146-5212b68d42e9.png">

I've tried to change power cable and power adapter but issue remains. How can I find out where is the problem?

**Comment by guymcswain** [comment]
A few observations:

1)  Your script assumes the `wid` of the waveform to transmit is always 0.  This is only the case after you first start up the daemon or after each `pigs wvclr`.

2) You are running a waveform repeatedly and it needs to be stopped explicitly before another wave can run.  In other words, running this script again may not change the waveform that is currently running.  Use `pigs wvhlt`.

**Comment by guymcswain** [comment]
Closing issue due to lack of response.
