### ISSUE TITLE
Make Install error on Alpine

### ISSUE THREAD

**Issue by Syriane-B** [joan2937/pigpio#483]
Hi, I'm trying to install your package on Alpine version of debian (home assistant installed on raspberry 3).
I have an error when i make install : 
```
gcc -03 -Wall -pthread -fpic -c -o pigpio.o pigpio.c
make: gcc: No such file or directory
make: *** [Makefile:48: pigpio.o] Error 127
```

Do you have any clue ?
Thanks

**Comment by guymcswain** [comment]
Are you doing this?
wget https://github.com/joan2937/pigpio/archive/master.zip

unzip master.zip
cd pigpio-master
make
sudo make install

**Comment by Syriane-B** [comment]
Yes and the error apear on the make command

**Comment by guymcswain** [comment]
You may want to search “make error 127”.
