### ISSUE TITLE
Python - I2C slave issue - Use of bsc_xfer and bsc_i2c

### ISSUE THREAD

**Issue by matbs24** [joan2937/pigpio#490]
I would use a Rpi 3B+ as I2C slave. I had the following issue: Each reply to master contains the previous byte put in the FIFO.  Slave is always a byte behind respect to what is supposed to send. 

I did a quick test to explain this:
I2C communication
Master: Arduino uno sending incremental byte every second. Starting from value 1

```
#include <Wire.h>

void setup()
{
   Wire.begin(); // join i2c bus as master
   Serial.begin(9600);  // start serial for output
   while(Serial.available() == 0) {
    }
   int mydata = Serial.read();
}

char strOut[17],strIn[17];

int x = 0;


   
void loop()
{   
  while (x < 20){
     if (++x > 9999999) x=0;
     sprintf(strOut, "Sending %d \n", x);
     Serial.print(strOut);
     
     Wire.beginTransmission(24); // transmit to device #24 = 0x18
     Wire.write(x);           // sends 16 bytes
     Wire.endTransmission();    // stop transmitting
     
     Wire.requestFrom(24, 1);    // request 6 bytes from slave device #8
  
     while (Wire.available()) { // slave may send less than requested
        char c = Wire.read(); // receive a byte as character
        sprintf(strIn, "Received %d \n", c);
        Serial.print(strIn);
     }
     delay(1000);
  }
  
}
```
Slave:Rpi 3B+ running pigpio deamon at 1 us. Acting as I2C slave. When one byte read request arrived replay back with the same byte

```
import time
import pigpio


SDA=18
SCL=19

_slave_address = 0x18

def i2c(id, tick):
   global pi

   s, b, d = pi.bsc_i2c(_slave_address)
   global stop
   if b:
        data = int.from_bytes(d,"big")
        print(data)
        print(pi.bsc_i2c(_slave_address,[data]))
        stop = stop+1
        
if __name__ == '__main__':

    pi = pigpio.pi()

    stop = 0

    if not pi.connected:
        exit()

    # Add pull-ups in case external pull-ups haven't been added

    pi.set_pull_up_down(SDA, pigpio.PUD_UP)
    pi.set_pull_up_down(SCL, pigpio.PUD_UP)

    # Respond to BSC slave activity

    e = pi.event_callback(pigpio.EVENT_BSC, i2c)

    pi.bsc_i2c(_slave_address) # Configure BSC as I2C slave

    time.sleep(25)

    e.cancel()

    pi.bsc_i2c(0) # Disable BSC peripheral

    pi.stop()
``

**Comment by matbs24** [comment]
![screenmsa](https://user-images.githubusercontent.com/32978885/135469026-54ce9e54-501b-4862-b477-a60815c595a8.jpeg)

**Comment by matbs24** [comment]
Furthermore I made a signal acquisition and I add a set of GPIO pin when entering the callback and this is the timing that partially explain the issue.
![Capture](https://user-images.githubusercontent.com/32978885/135469302-44b87b80-5739-43cd-b03f-d09b91cae360.JPG)

**Comment by matbs24** [comment]
Does anyone try to reproduce it?

**Comment by guymcswain** [comment]
I will take a look at this later today.  You are saying the data is getting transferred ok but is behind (index-1) from what you expect?

**Comment by matbs24** [comment]
Yes. They are one byte behind in my test.

**Comment by guymcswain** [comment]
From your arduino code it looks like your loop is: write, read, delay.  You should delay after write to allow time for Python client to service the BSC.

**Comment by matbs24** [comment]
OK. I got it, then it confirms my signal debugging. It can't answer in less then 2-3 ms.  Does exist a way to speed up? or make the BSC wait to answer back without using the not yet updated register?

**Comment by guymcswain** [comment]
Not really, considering you have a dependency on the network stack latency.   One application that I recall used the BSC as a ‘leader’.  The ‘follower’, in this case your arduino i2c master, polls for commands to do work then return results.  You have to develop your own protocol.
