### ISSUE TITLE
Importing the PiGPio to the Pi Pico on micropython on MacOS

### ISSUE THREAD

**Issue by jos149** [joan2937/pigpio#492]
Dear reader,

I want to control a LED strip with my pi pico.
A ran into this library and succesfully tested it with my pi 4. Does wat it should.
For the next step I want to write a python code and run this on my pi pico.
The problem I run into is: having downloaded the repository to my macbook and trying to run `make` gives me:

`pigpio-master % make
gcc -O3 -Wall -pthread -fpic -c -o pigpio.o pigpio.c
pigpio.c:59:10: fatal error: 'sys/sysmacros.h' file not found
#include <sys/sysmacros.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [pigpio.o] Error 1`

which raises the question: How would I install this library to my mac?
What I want to do is to run a python code telling:
`from machine import pigpio`
To be able to run the commands on my pi pico.

Any help would be appreciated.

**Comment by joan2937** [comment]
You can't run pigpio on the pico.  It only runs on Raspberry Pis.

I understand your confusion, just accept that the Raspberry Pico is not a Raspberry Pi.

I have written a simple daemon for the pico, but it is not compatible with micropython.

See http://abyz.me.uk/picod/ or https://github.com/joan2937/picod

**Comment by jos149** [comment]
Thanks for your quick reply.

Then I am still wondering: is it possible to import the pigpio library on macOS using the thonny software? How would you do it?

Same for the pico software:
I can download the library but will I get a similar error running 'make'?

**Comment by kanth1** [comment]
Am following this: when i execute below command on my mac
https://abyz.me.uk/rpi/pigpio/download.html


`user@XYZuser pigpio-master % make`
i get the below error: 
pigpio.c:59:10: fatal error: 'sys/sysmacros.h' file not found
#include <sys/sysmacros.h>
         ^~~~~~~~~~~~~~~~~
         
Can someone pls help here

**Comment by joan2937** [comment]
The main pigpio library only runs on a Raspberry Pi (which does not include the Pico). 

pigs and the pigpiod_if2 library may be used on Linux machines to allow control of the pigpio daemon (running on a Pi) from a networked computer.  pigs and the pigpiod_if2 library may perhaps run on Windows and Macs (but require user tailoring to do so).
