### ISSUE TITLE
SPI chip select and device tree overlays

### ISSUE THREAD

**Issue by gautamjain** [joan2937/pigpio#493]
Hi,

I applied a device tree overlay on the RPI4, in order to customize the SPI chip select lines.

`dtoverlay=spi0-2cs,cs0_pin=04,cs1_pin=27`

However, pigpio doesn't respect this change.  It continues to use the default SPI chip select lines.  I believe this is because the [chip select pins are hardcoded](https://github.com/joan2937/pigpio/blob/master/pigpio.c#L585) in `pigpio.c`. 

Do you have ideas on how this could be fixed?  Could pigpio (somehow) query the system to determine which chip select lines have been configured for the main/aux SPI buses?

**Comment by joan2937** [comment]
pigpio does not use the Linux SPI driver.

pigpio uses its own SPI driver which was written before the Linux SPI driver was available for the Pi.

For your use case I suggest you use the Linux SPI driver.

**Comment by gautamjain** [comment]
Oh got it. Thanks for the clarification.
