### ISSUE TITLE
Non-blocking serial open

### ISSUE THREAD

**Issue by radoslavilievm2m** [joan2937/pigpio#496]
Hello,
I am using the serial_open option for managing an USB modem remotely, which opens an ttyUSB device. 
The problem is, that if it restarts and the port is still open, it changes its name from ttyUSB0 to ttyUSB1, for example.

While using minicom, this problem doesn't occurs.

Thanks in advance.

**Comment by guymcswain** [comment]
serial_open api is just using sysfs.  If you are monitoring remotely you are going through a network port that could be hanging on to the resource (pure speculation).  Presumably, with minicom, you would normally logout which would release resources.

What does it mean “after it restarts”?  Are you closing the serial port?   Why does this matter if minicom is working for you?

**Comment by radoslavilievm2m** [comment]
Hi,
I found a solution to the problem - we have to check it is available, and if not, to close it and re-open it when it becomes available - if it. I'll do a PR about it shortly.
About the meaning of restarting - I mean restarting the USB modem, or simply detaching the cable.
I'm not just using minicom, because I am using the daemon to expose the communication (and not only) over TCP/IP and access it remotely by a PC.
