### ISSUE TITLE
Issue with Restarting pigpiod

### ISSUE THREAD

**Issue by rushmakes** [joan2937/pigpio#499]
I want to write a python script where I am calling a C executable(This C exe has i2c functionality based on pigpio)
Hence, before running C exe I am KILLING the pigpio daemon using:
`subprocess.run('if pgrep pigpiod; then sudo pkill -9 pigpiod; fi',shell=True,stdout=subprocess.DEVNULL)`

And after this I am again starting the daemon using:
`subprocess.run('if ! pgrep pigpiod; then sudo pigpiod ; fi',shell=True, stdout=subprocess.DEVNULL)`

Now to read the data from I2C device. while calling i2c read fucntion I am getting this error:
 `File "/usr/local/lib/python3.7/dist-packages/pigpio.py", line 2721, in i2c_open
    self.sl, _PI_CMD_I2CO, i2c_bus, i2c_address, 4, extents))
  File "/usr/local/lib/python3.7/dist-packages/pigpio.py", line 1063, in _pigpio_command_ext
    dummy, res = struct.unpack('12sI', sl.s.recv(_SOCK_CMD_LEN))
struct.error: unpack requires a buffer of 16 bytes`
Can anyone help me with this ?
The flow of my script:

1. import pigpio
2. pi=pigpio.pi()
3. Do some I2C writing
4. Kill PIGPIOD
5. Run C executable
6. Start PIGPIOD
7. reading I2C data from device
8. pi.stop()

PS: pi=pigpio.pi() is declared globally

**Comment by guymcswain** [comment]
This is not an intended use case for the library.  It is best that you find another way to solve your problem.
