### ISSUE TITLE
adapting pigpiod for Odroid

### ISSUE THREAD

**Issue by habakuk1979** [joan2937/pigpio#500]
hello!

great library you have there.

As we are pretty much out of interest witg our platform (infakt C2 on 5.14.19 Ubuntu 18.04) I wondered if it was possibel to adapt your pigpiod library with somewhat effort for the C2 in order to be able to run `node-red-node-pi-pgiod nodes` on it!

what do you thiink?

with kind regards

Habakuk

**Comment by joan2937** [comment]
pigpio is only supported on Raspberry Pi SoCs.
