### ISSUE TITLE
How to achieve 1.5hz hardware pwm ？

### ISSUE THREAD

**Issue by jiangzhuti** [joan2937/pigpio#501]
In my scenario, 1hz is too slow and 2hz is too fast. 

How can I use 1.5hz hardware pwm?

**Comment by joan2937** [comment]
You can't with the pigpio hardware PWM methods.  They only allow an integral Hz setting.

You can if you can use waves.

I give an example using pigs, you can achieve the same in Python and C.  I use >> to indicate output from pigs.
```
$ G=18
$ pigs m $G w
$ pigs wvag $((1<<$G)) 0 1500000 0 $((1<<$G)) 1500000
>> 2
$ pigs wvcre
>> 0
john@pi4b:~ $ pigs wvtxr 0
>> 5
```
![Screenshot from 2021-11-18 11-07-53](https://user-images.githubusercontent.com/5736953/142405099-21f0cb4c-133b-4b73-8d88-d7480e8c0e12.png)
