### ISSUE TITLE
Use of pigpio on jetson nano

### ISSUE THREAD

**Issue by janezlapajne** [joan2937/pigpio#515]
Can library also be used for jetson nano, because the command sudo apt-get install python-pigpio python3-pigpio throws me and error: E: Unable to locate package python3-pigpio? Download using pip installs pigpio library, but the deamon still won't start. Which steps should I take to build jetson version from source and is this even possible? Thank you!

What I tried so far is that I followed instructions on how to build from [source](http://abyz.me.uk/rpi/pigpio/download.html), but after I run pigpio deamon it throws me a message saying: Sorry, this system does not appear to be a raspberry pi. aborting. Can't initialize pigpio library.

**Comment by guymcswain** [comment]
> Can library also be used for jetson nano

No.  `pigpio` is written specifically for the Raspberry Pi BCM2835/BCM2711 based boards.
