### ISSUE TITLE
Informational  Query:  Expected CPU loading when PiGPIOd should be effectively idle?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [joan2937/pigpio#521]
Informational  Query:  Expected CPU loading when PiGPIOd should be effectively idle?  I am seeing CPU loading between 6 and 9 % when the PiGPIOd process should be effectively idle.  Could you provide some insight as to why or how this is the case?  Not an issue per se, but seeking understanding on how or why this is the case?

**Comment by joan2937** [comment]
The daemon is sampling the levels of GPIO 0-31 two hundred thousand times a second (default values).  The background loading is the time taken to go through those levels to see if anything has changed.

http://abyz.me.uk/rpi/pigpio/cif.html#gpioCfgClock

**Comment by Jibun-no-Kage** [comment]
Ah, thanks.  This is great information.
