### ISSUE TITLE
pigpio on arch AArch64

### ISSUE THREAD

**Issue by aa755** [joan2937/pigpio#524]
Due to some issues with raspbian on my rpi 3b+, I decided to install arch linux AArch64 version using the official instructions [here](https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-3):
Note that I used the url at the end of the installation instructions, which suggest to use the following url instead of the arm7 version: http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-aarch64-latest.tar.gz

Then I installed pigpio from AUR. But I get:
```
[alarm@alarm yay]$ pigpiod
2022-03-27 19:04:55 gpioHardwareRevision: unknown revision=0
2022-03-27 19:04:55 initCheckPermitted: 
+---------------------------------------------------------+
|Sorry, this system does not appear to be a raspberry pi. |
|aborting.                                                |
+---------------------------------------------------------+
```
I know I can look into the source code and disable that check. But I would appreciate if somebody has already tried to run pigpio on arch linux AArch64 version, and can share their experience

**Comment by guymcswain** [comment]
> AArch64 Installation
This provides an installation using the mainline kernel and U-Boot. Use this installation only if you have no dependencies on the closed source vendor libraries shipped in the ARMv7 release.

pigpio is ***dependent*** upon 'the closed source vendor libraries '.
