### ISSUE TITLE
sigHandler: Unhandled signal 2, terminating

### ISSUE THREAD

**Issue by darshitagrawal** [joan2937/pigpio#528]
I am working on interfacing dht11 with Raspberry Pi. My code is as per this link: https://github.com/jimstudt/dht11-pigpio/blob/master/dht11-pigpio.c. My concern is when I press Ctrl+C, I get the error "Unhandled Signal 2, terminating" and after that I cannot write further commands on my linux terminal. Can anyone tell me what should I do?

![162255367-11d24822-d49a-44cc-a042-29100eebb8a0](https://user-images.githubusercontent.com/89857796/164059423-fd068017-5ebd-436d-ac3c-b29363963500.jpg)

**Comment by guymcswain** [comment]
By default, pigpio sets up to handle all signals but you have to attach a function to the signal - in this case SIGINT - using `gpioSetSignalFunc`.  Try `gpioSetSignal(SIGINT, cleanup)` and remove `atexit(cleanup)`.  (You may need to add exit() at the end of cleanup.)

Your other choice is the disable this default behavior and to handle the signal directly in your code.

**Comment by darshitagrawal** [comment]
I tried putting this in my code. But I still cannot execute further commands in my linux terminal. I can type the commands plainly but they are not being executed. What should I do?

**Comment by guymcswain** [comment]
Do this before you invoke `gpioInitialise()`:
```
int cfg = gpioCfgGetInternals();
cfg |= PI_CFG_NOSIGHANDLER;  // (1<<10)
gpioCfgSetInternals(cfg);
```

**Comment by guymcswain** [comment]
@darshitagrawal , I have posted an improved signal handling topic branch on the repo named `signals`.  Can you test this issue against the `signals` branch?
```bash
wget https://github.com/joan2937/pigpio/archive/signals.zip
unzip signals.zip
cd pigpio-signals
make
sudo make install
```
