### ISSUE TITLE
Lower sample rates beyond gpioCfgClock?

### ISSUE THREAD

**Issue by sectokia** [joan2937/pigpio#538]
Is there any way the sample rate can be lowered below the settings in gpioCfgClock?

I would like to see application where you can lower this down to say, 1000hz sampling, mainly to get the cpu usage down. 

I am seeing about a 14% CPU minimum on raspberry pi zero, even if you are not doing anything but waiting for interrupt etc.

**Comment by guymcswain** [comment]
So much functionality in pigpio is affected by lowering the sample rate that it would render it more or less useless.  Therefore, there is an option to turn it off completely:
`sudo pigpiod -m`
