### ISSUE TITLE
run as user

### ISSUE THREAD

**Issue by christianrauch** [joan2937/pigpio#549]
I am trying to use the library as a regular user (without root or sudo).

On my system, this requires to be in the `kmem` group and give this group write access:
```sh
ls -alh /dev/mem
# crw-r----- 1 root kmem 1, 1 Okt 16 14:08 /dev/mem
sudo chmod g+w /dev/mem
ls -alh /dev/mem
# crw-rw---- 1 root kmem 1, 1 Okt 16 14:08 /dev/mem
sudo usermod -a -G kmem $USER
```

After this, I am still getting:
```
+---------------------------------------------------------+
|Sorry, you don't have permission to run this program.    |
|Try running as root, e.g. precede the command with sudo. |
+---------------------------------------------------------+
```

Do I need additional rights to access `/dev/mem` as a regular user? Could this be documented?

**Comment by guymcswain** [comment]
Root privilege required for at least the ability to mmap the peripheral registers and accessing the mailbox registers handling lower level firmware apis.  It's not so simple or I'm sure it would have been done already.
