### ISSUE TITLE
Initialization issue on debian 12 bookworm

### ISSUE THREAD

**Issue by montazek** [joan2937/pigpio#583]
Using Raspberry 2B on Debian 12 Bookworm 
 6.1.0-11-armmp #1 SMP Debian 6.1.38-4 (2023-08-08) armv7l GNU/Linux
(from https://raspi.debian.net/tested-images/)

After installation latest version when trying to running sudo ./x_pigpio i get:

2023-08-21 09:59:56 initPeripherals: mmap gpio failed (Operation not permitted)
pigpio initialisation failed.

Is it possible to get it running on debian 12?

**Comment by guymcswain** [comment]
I have no idea.

**Comment by guymcswain** [comment]
The bookworm release of Raspberry Pi OS is what you need.  Rumor has it its release is imminent.
