### ISSUE TITLE
Failed on Rpi2 and AlpineLinux

### ISSUE THREAD

**Issue by blahlt** [joan2937/pigpio#590]
Failed to run on Raspberry Pi 2 Model B V1.1 (OS: Alpine Linux (alpine-rpi-3.18.4-armv7))

I always get an error message:
initPeripherals: mmap gpio failed (Invalid argument)
Can't initialise pigpio library

Are there any solutions?

**Comment by guymcswain** [comment]
I think the memory mapping requires assistance from the VPU firmware (mailbox registers).  I’m not aware of how to enable non RasperryPi OS to do this.

**Comment by blahlt** [comment]
Yeah, it works on Raspberry Pi OS, but not on Alpine Linux :(
