### ISSUE TITLE
Adding new functions to the library 

### ISSUE THREAD

**Issue by susWorld** [joan2937/pigpio#610]
Hi,
We encountered an issue where we needed to implement a function within the pigpio library to flush the DMA in order to resolve the PI_INIT_FAILED error so we don't have to power cycle the pi. Since the library hasn't been updated since 2021, I'm unsure if my PR will be accepted. Therefore, I wanted to ask here first: can we add our function to the library code?

**Comment by guymcswain** [comment]
> ... in order to resolve the PI_INIT_FAILED error ...

Can you reference an issue # in this repository or be more specific?

**Comment by susWorld** [comment]
not going to merge my changes
