### ISSUE TITLE
Cross-compiling should be easier

### ISSUE THREAD

**Issue by cashpipeplusplus** [joan2937/pigpio#91]
I am able to cross-compile for the Raspberry pi like this:

```sh
CROSS_PREFIX=arm-linux-gnueabi
make \
  CC=$CROSS_PREFIX-gcc \
  SHLIB="$CROSS_PREFIX-gcc -shared" \
  AR=$CROSS_PREFIX-ar \
  RANLIB=$CROSS_PREFIX-ranlib \
  SIZE=$CROSS_PREFIX-size \
  STRIPLIB=$CROSS_PREFIX-strip
```

This is a lot of variables to specify.  It would be easier if:

1. Some of the redundancies were eliminated (using $CC in SHLIB, for example)
2. All of the tool names were constructed with a common variable (such as CROSS_PREFIX, which would be blank by default)

I also have difficulty installing into my cross-compile environment due to the use of `install -s` to strip binaries.  `install` tries to run the host compiler's strip command, which fails for cross-compiled binaries.  It would be very helpful if `install -s` were not used.  Binaries could be stripped by `$STRIP` or similar in build rules instead.

If there are no objections, I will submit a PR to address these issues.

**Comment by joan2937** [comment]
I welcome anything which makes life easier as long as it doesn't break anything and I have a vague understanding of what it is doing and how it works.  I'll certainly have a look.

I'm pushing out a new version shortly.
