### ISSUE TITLE
bbI2CZip: wrong return code by PI_I2C_WRITE

### ISSUE THREAD

**Issue by tnogueira** [joan2937/pigpio#99]
Should line 

https://github.com/joan2937/pigpio/blob/master/pigpio.c#L1038

read instead: **_else status = PI_BAD_I2C_WLEN;_**  ?

**Comment by joan2937** [comment]
You are right.  I will change line 10385 as you suggest for the next version (V59).

I have no timescale for that release at the moment.

**Comment by joan2937** [comment]
Should be fixed in the now released V59.

**Comment by joan2937** [comment]
Assumed fixed.
